import OddZetaMixed
import OddZetaMixed.TrustAudit

audit_project_axioms OddZetaMixed

#check OddZetaMixed.h158ArithmeticCertifiedRate
#check OddZetaMixed.h158_eventually_primitive_det_small
#check OddZetaMixed.h158_eventually_primitive_polynomial_small
#check OddZetaMixed.exists_irrational_riemannZeta_seven_to_nineteen
#print axioms OddZetaMixed.h158ArithmeticCertifiedRate
#print axioms OddZetaMixed.h158_eventually_primitive_polynomial_small
#print axioms OddZetaMixed.exists_irrational_riemannZeta_seven_to_nineteen

#check OddZetaMixed.h158_seven_irrational_of_rates
#check OddZetaMixed.h158ModulusWeight_uniform_envelope_abs
#check OddZetaMixed.h158AdaptiveMoment_le_of_compact
#check OddZetaMixed.h158AnalyticBound_of_compact_phase_ceiling
#check OddZetaMixed.h158AnalyticCertifiedRate
#print axioms OddZetaMixed.h158AnalyticCertifiedRate
#check OddZetaMixed.h158PrimitiveCost_rate_of_three_bands
#check OddZetaMixed.H158MiddleCells.Certificate.primitive_cost_le_majorant
#check OddZetaMixed.sevenZeta_irrational_iff_standard
#check OddZetaMixed.h158PrimitiveCost_rate_of_generic_profile
#check OddZetaMixed.h158PrimitiveCost_rate_of_affine_profile
#check OddZetaMixed.h158_eventually_avoid_rational_walls

-- Printing the types is essential: axiom auditing alone cannot detect a missing
-- mathematical input that has merely been moved into a theorem argument.
#check OddZetaMixed.h158Kernel_degree
#check OddZetaMixed.momentMatrix_degree
#check OddZetaMixed.infinite_prime_gate
#check OddZetaMixed.SignedMinors.minor_valuation_lower
#check OddZetaMixed.global_arithmetic_rate
#check OddZetaMixed.same_sequence_negative_rate
#check OddZetaMixed.integer_obstruction_of_infinite_good_log
#check OddZetaMixed.no_integer_sequence_with_global_budget
#check OddZetaMixed.evenBasis_integer_valued
#check OddZetaMixed.rank_two_entry_degree_bound
#check OddZetaMixed.protected_fifth_power_dvd
#check OddZetaMixed.RectangularExpansion.det_mul_valuation_lower
#check OddZetaMixed.RectangularExpansion.det_mul_mul_transpose_valuation_lower
#check OddZetaMixed.gate_squares_injective
#check OddZetaMixed.gateEvenEvaluation_det_ne_zero
#check OddZetaMixed.weighted_gate_det_ne_zero
#check OddZetaMixed.h158_partial_fractions
#check OddZetaMixed.h158_principal_coefficients_unique
#check OddZetaMixed.h158_principal_coefficients_reflection
#check OddZetaMixed.h158_residue_sum_zero
#check OddZetaMixed.hasSum_h158EntryReal_fourthDerivative
#check OddZetaMixed.h158Functional_eq_seven
#check OddZetaMixed.h158SevenMatrix_det_eval
#check OddZetaMixed.sevenZetaValues_ofReal
#check OddZetaMixed.exists_primitive_normalization_with_gauss_cost
#check OddZetaMixed.h158_exists_primitive_data
#check OddZetaMixed.rowScaling_fee_exact
#check OddZetaMixed.h158Primitive_normalization
#check OddZetaMixed.h158_actual_rational_specialization_clearing
#check OddZetaMixed.UpperQuadraticExpRateOn.log_abs
#check OddZetaMixed.H158ArithmeticBound
#check OddZetaMixed.H158AnalyticBound
#check OddZetaMixed.H158RationalGate
#check OddZetaMixed.h158_seven_irrational_of_three_inputs
#check OddZetaMixed.h158PrincipalCoefficients_top_eq
#check OddZetaMixed.h158PoleComplement_top_padicValRat
#print OddZetaMixed.H158ArithmeticBound
#print OddZetaMixed.H158AnalyticBound
#print OddZetaMixed.H158RationalGate
#check OddZetaMixed.h158LocalPrincipal_congruence
#check OddZetaMixed.h158Gate_principal_coeff_nonneg
#check OddZetaMixed.h158Gate_constant_remainder_integral
#check OddZetaMixed.h158GateWeight_unit
#check OddZetaMixed.h158Gate_double_jets
#check OddZetaMixed.h158Gate_local_reduction_exists
#check OddZetaMixed.h158GateReduction_ne_zero_iff
#check OddZetaMixed.h158Gate_full_entry_reduction_exists
#check OddZetaMixed.h158GateLeadingEntry_cast_matrix
#check OddZetaMixed.h158Gate_rational_specialization_ne_zero
#check OddZetaMixed.h158_rational_gate
#check OddZetaMixed.h158Gate_rational_determinant_valuation
#check OddZetaMixed.h158_seven_irrational_of_rate_bounds
#check OddZetaMixed.h158Functional_eq_nonnegative_sum
#check OddZetaMixed.h158EntryComplex_cutoff_shift
#check OddZetaMixed.h158ContourKernel_eq
#check OddZetaMixed.h158ContourIntegrand_integer_residue
#check OddZetaMixed.hasSum_h158Contour_residue_series
#print axioms OddZetaMixed.h158_rational_gate
#print axioms OddZetaMixed.h158Gate_rational_determinant_valuation
#print axioms OddZetaMixed.h158_seven_irrational_of_rate_bounds
#check OddZetaMixed.h158EntryComplex_norm_le_decay
#check OddZetaMixed.h158ClosingEdges_tendsto_zero
#check OddZetaMixed.h158SevenMatrix_det_coeff_den_prime_support
#check OddZetaMixed.h158PrimitiveScalar_den_prime_support
#check OddZetaMixed.h158PrimitiveCost_le_finite_gauss_sum
#print axioms OddZetaMixed.h158ClosingEdges_tendsto_zero
#print axioms OddZetaMixed.h158PrimitiveCost_le_finite_gauss_sum
#check OddZetaMixed.h158Gate_formal_gauss_valuation
#check OddZetaMixed.h158Gate_primitive_scalar_valuation
#print axioms OddZetaMixed.h158Gate_formal_gauss_valuation
#print axioms OddZetaMixed.h158Gate_primitive_scalar_valuation
#check OddZetaMixed.h158LocalPrincipal_eq_base_mul_coeff
#check OddZetaMixed.h158SevenMatrix_eq_jetFunctional
#check OddZetaMixed.h158SevenMatrix_taylor_factorization
#check OddZetaMixed.h158SevenMatrix_eq_residue_factorization
#check OddZetaMixed.h158ScaledTaylorEvaluation_coeff_nonneg
#check OddZetaMixed.h158_scaled_cluster_factorization
#check OddZetaMixed.h158_scaled_determinant
#check OddZetaMixed.h158RowFee_exact
#check OddZetaMixed.h158VerticalIntegrand_integrable
#check OddZetaMixed.h158VerticalIntegral_truncation_error
#check OddZetaMixed.h158NormalizedClockwiseRectangleIntegral_tendsto
#check OddZetaMixed.weighted_prime_quadratic_rate
#check OddZetaMixed.h158_prime_content_three_bands_rate
#check OddZetaMixed.LocalJetValuation.truncated_division
#check OddZetaMixed.LocalJetValuation.h158_base_laurent_floor_from_class_counts
#check OddZetaMixed.LocalJetValuation.h158_residueClusterMoment_floor
#check OddZetaMixed.LocalJetValuation.h158_residue_minor_signed_cost
#check OddZetaMixed.LocalJetValuation.formal_det_mul_mul_transpose_floor
#check OddZetaMixed.LocalJetValuation.formal_unscale
#check OddZetaMixed.h158_scaled_assembled_fin_factorization
#check OddZetaMixed.h158_primitive_cost_of_assembled_minor_floor
#check OddZetaMixed.h158_pair_fold_identity
#check OddZetaMixed.h158CenteredBasis_central_odd_coeff_zero
#check OddZetaMixed.h158ClockwiseRectangle_residue_identity
#check OddZetaMixed.h158NormalizedVerticalIntegral_eq_functional
#check OddZetaMixed.rank_two_factorial_subquadratic
#check OddZetaMixed.UpperQuadraticExpRateOn.of_factorial_majorant
#check OddZetaMixed.LocalJetValuation.h158_residueClusterMoment_floor_at_integer_anchor
#check OddZetaMixed.FormalBlockSelection.formal_block_minor_allocation_floor
#check OddZetaMixed.FormalBlockSelection.h158_det_unfolded_allocation_floor
#check OddZetaMixed.FormalBlockSelection.h158_primitive_cost_unfolded_allocation
#check OddZetaMixed.h158Functional_det_abs_le_modulusMoments
#check OddZetaMixed.h158Functional_det_abs_le_diagonalAbsoluteIntegrals
#check OddZetaMixed.h158_paired_residue_block_floor
#check OddZetaMixed.h158_central_block_compression
#check OddZetaMixed.h158_central_even_block_floor
#check OddZetaMixed.h158_scaled_reflection_orbit_factorization
#check OddZetaMixed.h158_scaled_folded_fin_factorization
#check OddZetaMixed.h158_folded_minor_allocation_floor
#check OddZetaMixed.h158_primitive_cost_folded_threshold
#check OddZetaMixed.h158PrimitiveCost_le_explicit_budget
#check OddZetaMixed.H158SmallPrimeBudget.smallPrimeCost_upperQuadraticRate
#check OddZetaMixed.LocalJetValuation.h158_numerator_count_floor
#check OddZetaMixed.LocalJetValuation.h158_denominator_count_floor
#check OddZetaMixed.LocalJetValuation.h158_normalized_class_count_lower
#check OddZetaMixed.h158ClassCost_reflection
#check OddZetaMixed.h158ClassCost_le_twenty
#check OddZetaMixed.H158IntegerValuedJets.h158_entry_floor_twenty_unconditional
#check OddZetaMixed.H158IntegerValuedJets.h158_primitiveCost_le_forty
#check OddZetaMixed.h158ScaledMonicEven_normalization
#check OddZetaMixed.h158AdaptiveMonic_det
#check OddZetaMixed.h158AdaptiveMonic_det_abs_le_modulusMoments
#check OddZetaMixed.h158ScaledAdaptiveContour_norm_sq_le
#check OddZetaMixed.h158PairMoment_singleton_minor_plateau
#check OddZetaMixed.h158CentralEvenMoment_singleton_minor_plateau
#check OddZetaMixed.h158_folded_hybrid_det_minimum_floor
#check OddZetaMixed.H158ExceptionalPrimes.exceptionalPrimeCost_upperQuadraticRate
#check OddZetaMixed.h158BasisNormalization_log_rate
#check OddZetaMixed.h158BasisNormalization_eventually_exp_bounds
#check OddZetaMixed.h158ClassCost_eq_unshifted_add_error
#check OddZetaMixed.h158ClassCost_unshifted_l1
#check OddZetaMixed.h158_unshifted_threshold_error_le
#check OddZetaMixed.h158_primitive_cost_truncated_folded_threshold
#check OddZetaMixed.h158FoldedWeight_unshifted_l1
#check OddZetaMixed.h158_primitive_cost_unshifted_threshold
