"""Kernel certificates for the explicitly authorized uniform +1 phase ceiling.

One shared partition serves all 16 endpoints. Each generated batch has at most
eight spatial cells. Only exact Fraction calculations are used; Lean checks
the elementary witnesses, numerical comparisons, and full interval coverage.
"""

import argparse
import json

from generate_compact_phase import SOURCE, PROJECT, Q, fmt, log_bounds, pair_bound, phase_bounds
from generate_compact_phase_endpoints import emit_join
from generate_compact_phase_tables import Tables, emit_phase, compile_serial


def common_cells(records):
    rows = [(Q(r["theta"]), Q(r["ceiling"]), list(map(Q, r["roots"]))) for r in records]
    cells = []

    def visit(l, r):
        _, U = phase_bounds(l, r)
        margins = [ceiling+1-U-theta/8*sum(
            (log_bounds(pair_bound(l, r, a))[2] for a in roots), Q(0))
            for theta, ceiling, roots in rows]
        if min(margins) >= 0:
            cells.append((l, r, min(margins)))
            return
        assert r-l > Q(1, 2**18), "Unexpectedly fine partition"
        c = (l+r)/2
        visit(l, c)
        visit(c, r)

    visit(Q(0), Q(96))
    return cells


def generate_batch(records, cells, batch):
    e = Tables()
    e.put("-- Generated by generate_compact_phase_slack.py; explicit ceiling allowance is +1.\n"
          "import OddZetaMixed.H158CompactPhaseSlackEvaluator\n\n"
          "noncomputable section\n"
          "set_option maxRecDepth 100000\n"
          "set_option maxHeartbeats 0\n"
          "set_option Elab.async false\n"
          f"namespace OddZetaMixed.CompactPhase.SlackBatch{batch:02d}\n"
          "open Finset Certificates\n")
    for j, (l, r, _) in enumerate(cells):
        phase_name, U = emit_phase(e, j, l, r)
        rows = []
        for b in range(8):
            row = []
            for a in map(Q, records[2*b]["roots"]):
                k, lo, hi = log_bounds(pair_bound(l, r, a))
                row.append(f"⟨{k}, {fmt(lo)}, {fmt(hi)}⟩")
            rows.append("![" + ", ".join(row) + "]")
        e.put(f"def pairData_{j} : Fin 8 → Fin 4 → LogWitness :=\n  ![" + ",\n    ".join(rows) + "]\n")
        e.put(f"theorem pairChecks_{j} : ∀ b i,\n"
              f"    logWitnessCheck (pairBound {fmt(l)} {fmt(r)} (h158PhaseRoots b i)) (pairData_{j} b i) = true := by\n"
              "  decide +kernel\n")
        e.put(f"def pairLogs_{j} (b : Fin 8) := logEnclosures\n"
              f"  (fun i => pairBound {fmt(l)} {fmt(r)} (h158PhaseRoots b i)) (pairData_{j} b) (pairChecks_{j} b)\n")
        e.put(f"theorem cell_{j} (b : Fin 8) (side : Fin 2) {{s : ℝ}}\n"
              f"    (hs : ({fmt(l)} : ℚ) ≤ s ∧ s ≤ ({fmt(r)} : ℚ))\n"
              "    (hpositive : ∀ i, 0 < h158AdaptivePairModulus 75 (h158PhaseRoots b i : ℝ) s) :\n"
              "    h158PhasePotential (fun i => (h158PhaseRoots b i : ℝ)) (endpointTheta b side : ℝ) s ≤\n"
              "      (h158CompactEndpointCeiling b side : ℝ)+1 := by\n"
              f"  exact potential_endpoint_cell_add_one {fmt(l)} {fmt(r)} {fmt(U)} (by decide +kernel)\n"
              f"    (fun _ ht => {phase_name} (by simpa using ht)) pairLogs_{j}\n"
              "    (by decide +kernel) b side hs hpositive\n")
    e.put("theorem covered_endpoints (b : Fin 8) (side : Fin 2) {s : ℝ}\n"
          f"    (hs : ({fmt(cells[0][0])} : ℚ) ≤ s ∧ s ≤ ({fmt(cells[-1][1])} : ℚ))\n"
          "    (hpositive : ∀ i, 0 < h158AdaptivePairModulus 75 (h158PhaseRoots b i : ℝ) s) :\n"
          "    h158PhasePotential (fun i => (h158PhaseRoots b i : ℝ)) (endpointTheta b side : ℝ) s ≤\n"
          "      (h158CompactEndpointCeiling b side : ℝ)+1 := by")
    emit_join(e, [(l, r) for l, r, _ in cells], [f"cell_{j} b side" for j in range(len(cells))], True)
    e.put(f"\nend OddZetaMixed.CompactPhase.SlackBatch{batch:02d}\n")
    target = PROJECT / f"OddZetaMixed/H158CompactPhaseSlackBatch{batch:02d}.lean"
    target.write_text("\n".join(e.lines))
    print(json.dumps({"output": str(target), "cells": len(cells), "endpoint_checks": 16*len(cells),
                      "interval": [str(cells[0][0]), str(cells[-1][1])], "bytes": target.stat().st_size,
                      "atan_orders": dict(e.orders)}), flush=True)
    return target


def generate(batch_size):
    records = json.loads(SOURCE.read_text())["rank_two_phase_replay"]["records"]
    assert len(records) == 16
    cells = common_cells(records)
    batches = [cells[start:start+batch_size] for start in range(0, len(cells), batch_size)]
    targets = [generate_batch(records, batch, i) for i, batch in enumerate(batches)]
    e = Tables()
    e.put("-- Generated by generate_compact_phase_slack.py. This proves M(theta)+1, not M(theta).")
    for target in targets:
        e.put(f"import OddZetaMixed.{target.stem}")
    e.put("\n/-! The full compact domain with the explicitly authorized uniform +1 allowance.")
    e.put("The corresponding product of 2*n rows loses 2 in its quadratic exponent. -/\n")
    e.put("noncomputable section\nnamespace OddZetaMixed\nopen CompactPhase\n")
    e.put("theorem h158CompactPhase_endpoints_add_one (b : Fin 8) (side : Fin 2) {s : ℝ}\n"
          "    (hs : 0 ≤ s ∧ s ≤ 96)\n"
          "    (hpositive : ∀ i, 0 < h158AdaptivePairModulus 75 (h158PhaseRoots b i : ℝ) s) :\n"
          "    h158PhasePotential (fun i => (h158PhaseRoots b i : ℝ)) (endpointTheta b side : ℝ) s ≤\n"
          "      (h158CompactEndpointCeiling b side : ℝ)+1 := by")
    emit_join(e, [(b[0][0], b[-1][1]) for b in batches],
              [f"SlackBatch{j:02d}.covered_endpoints b side" for j in range(len(batches))], True)
    e.put("\ntheorem h158CompactPhase_bin_add_one (b : Fin 8) {theta s : ℝ}\n"
          "    (hl : (b.val : ℝ)/4 ≤ theta) (hr : theta ≤ ((b.val : ℝ)+1)/4)\n"
          "    (hs : 0 ≤ s ∧ s ≤ 96)\n"
          "    (hpositive : ∀ j, 0 < h158AdaptivePairModulus 75 (h158PhaseRoots b j : ℝ) s) :\n"
          "    h158PhasePotential (fun j => (h158PhaseRoots b j : ℝ)) theta s ≤ h158CompactCeiling b theta+1 := by\n"
          "  apply h158CompactPhase_of_endpoints_add b hl hr\n"
          "  · simpa [endpointTheta] using h158CompactPhase_endpoints_add_one b 0 hs hpositive\n"
          "  · simpa [endpointTheta] using h158CompactPhase_endpoints_add_one b 1 hs hpositive\n")
    e.put("theorem h158CompactPhase_selected_le_add_one {theta s : ℝ}\n"
          "    (htheta : 0 ≤ theta ∧ theta < 2) (hs : 0 ≤ s ∧ s ≤ 96)\n"
          "    (hpositive : ∀ j, 0 < h158AdaptivePairModulus 75 (h158PhaseSelectedRoots theta j : ℝ) s) :\n"
          "    h158PhasePotential (fun j => (h158PhaseSelectedRoots theta j : ℝ)) theta s ≤ h158PhaseCeiling theta+1 := by\n"
          "  rw [← h158CompactCeiling_selected_eq htheta]\n"
          "  have hbin := h158PhaseBin_mem htheta\n"
          "  exact h158CompactPhase_bin_add_one (h158PhaseBin theta) hbin.1 hbin.2.le hs hpositive\n")
    e.put("theorem h158CompactPhase_selected_le_add_one_offRoots {theta s : ℝ}\n"
          "    (htheta : 0 ≤ theta ∧ theta < 2) (hs : 0 ≤ s ∧ s ≤ 96)\n"
          "    (hne : ∀ j, s ≠ (h158PhaseSelectedRoots theta j : ℝ)) :\n"
          "    h158PhasePotential (fun j => (h158PhaseSelectedRoots theta j : ℝ)) theta s ≤ h158PhaseCeiling theta+1 :=\n"
          "  h158CompactPhase_selected_le_add_one htheta hs\n"
          "    (h158PhaseRoots_pair_pos (h158PhaseBin theta) hs.1 hne)\n")
    e.put("theorem h158CompactPhase_row_ceiling_add_one (n : ℕ) (hn : 1 ≤ n) (i : Fin (2*n)) :\n"
          "    ∃ a : Fin 4 → ℚ, (∀ j, 0 ≤ (a j : ℝ) ∧ (a j : ℝ) ≤ 20) ∧\n"
          "      ∀ s : ℝ, 0 ≤ s → s ≤ 96 → (∀ j, 0 < h158AdaptivePairModulus 75 (a j : ℝ) s) →\n"
          "        h158PhasePotential (fun j => (a j : ℝ)) (h158PhaseCeilingTheta n i.val) s ≤\n"
          "          h158PhaseCeiling (h158PhaseCeilingTheta n i.val)+1 := by\n"
          "  refine ⟨h158PhaseSelectedRoots (h158PhaseCeilingTheta n i.val), ?_, ?_⟩\n"
          "  · intro j\n"
          "    exact ⟨(h158PhaseSelectedRoots_bounds _ j).1.le, (h158PhaseSelectedRoots_bounds _ j).2.le⟩\n"
          "  · intro s hs0 hs96 hp\n"
          "    exact h158CompactPhase_selected_le_add_one\n"
          "      (h158PhaseCeilingTheta_mem n i.val (by omega) i.isLt) ⟨hs0, hs96⟩ hp\n\n"
          "end OddZetaMixed\n")
    target = PROJECT / "OddZetaMixed/H158CompactPhaseSlack.lean"
    target.write_text("\n".join(e.lines))
    targets.append(target)
    print(json.dumps({"shared_cells": len(cells), "endpoint_checks": 16*len(cells),
                      "minimum_rational_margin": str(min(m for _, _, m in cells)),
                      "allowance_per_row": 1, "quadratic_rate_allowance": 2,
                      "lean_certificate": "requires successful compilation"}), flush=True)
    return targets


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--batch-size", type=int, default=8, choices=range(1, 9))
    parser.add_argument("--compile", action="store_true", help="Compile at most one generated file at a time")
    args = parser.parse_args()
    targets = generate(args.batch_size)
    if args.compile:
        compile_serial(targets)
