-- Generated by generate_compact_phase_slack.py. This proves M(theta)+1, not M(theta).
import OddZetaMixed.H158CompactPhaseSlackBatch00
import OddZetaMixed.H158CompactPhaseSlackBatch01
import OddZetaMixed.H158CompactPhaseSlackBatch02

/-! The full compact domain with the explicitly authorized uniform +1 allowance.
The corresponding product of 2*n rows loses 2 in its quadratic exponent. -/

noncomputable section
namespace OddZetaMixed
open CompactPhase

theorem h158CompactPhase_endpoints_add_one (b : Fin 8) (side : Fin 2) {s : ℝ}
    (hs : 0 ≤ s ∧ s ≤ 96)
    (hpositive : ∀ i, 0 < h158AdaptivePairModulus 75 (h158PhaseRoots b i : ℝ) s) :
    h158PhasePotential (fun i => (h158PhaseRoots b i : ℝ)) (endpointTheta b side : ℝ) s ≤
      (h158CompactEndpointCeiling b side : ℝ)+1 := by
  apply interval_join (m := ((27/2) : ℚ)) ?_ ?_ hs
  · intro hs
    exact SlackBatch00.covered_endpoints b side (by simpa using hs) hpositive
  · intro hs
    apply interval_join (m := ((39/2) : ℚ)) ?_ ?_ hs
    · intro hs
      exact SlackBatch01.covered_endpoints b side (by simpa using hs) hpositive
    · intro hs
      exact SlackBatch02.covered_endpoints b side (by simpa using hs) hpositive

theorem h158CompactPhase_bin_add_one (b : Fin 8) {theta s : ℝ}
    (hl : (b.val : ℝ)/4 ≤ theta) (hr : theta ≤ ((b.val : ℝ)+1)/4)
    (hs : 0 ≤ s ∧ s ≤ 96)
    (hpositive : ∀ j, 0 < h158AdaptivePairModulus 75 (h158PhaseRoots b j : ℝ) s) :
    h158PhasePotential (fun j => (h158PhaseRoots b j : ℝ)) theta s ≤ h158CompactCeiling b theta+1 := by
  apply h158CompactPhase_of_endpoints_add b hl hr
  · simpa [endpointTheta] using h158CompactPhase_endpoints_add_one b 0 hs hpositive
  · simpa [endpointTheta] using h158CompactPhase_endpoints_add_one b 1 hs hpositive

theorem h158CompactPhase_selected_le_add_one {theta s : ℝ}
    (htheta : 0 ≤ theta ∧ theta < 2) (hs : 0 ≤ s ∧ s ≤ 96)
    (hpositive : ∀ j, 0 < h158AdaptivePairModulus 75 (h158PhaseSelectedRoots theta j : ℝ) s) :
    h158PhasePotential (fun j => (h158PhaseSelectedRoots theta j : ℝ)) theta s ≤ h158PhaseCeiling theta+1 := by
  rw [← h158CompactCeiling_selected_eq htheta]
  have hbin := h158PhaseBin_mem htheta
  exact h158CompactPhase_bin_add_one (h158PhaseBin theta) hbin.1 hbin.2.le hs hpositive

theorem h158CompactPhase_selected_le_add_one_offRoots {theta s : ℝ}
    (htheta : 0 ≤ theta ∧ theta < 2) (hs : 0 ≤ s ∧ s ≤ 96)
    (hne : ∀ j, s ≠ (h158PhaseSelectedRoots theta j : ℝ)) :
    h158PhasePotential (fun j => (h158PhaseSelectedRoots theta j : ℝ)) theta s ≤ h158PhaseCeiling theta+1 :=
  h158CompactPhase_selected_le_add_one htheta hs
    (h158PhaseRoots_pair_pos (h158PhaseBin theta) hs.1 hne)

theorem h158CompactPhase_row_ceiling_add_one (n : ℕ) (hn : 1 ≤ n) (i : Fin (2*n)) :
    ∃ a : Fin 4 → ℚ, (∀ j, 0 ≤ (a j : ℝ) ∧ (a j : ℝ) ≤ 20) ∧
      ∀ s : ℝ, 0 ≤ s → s ≤ 96 → (∀ j, 0 < h158AdaptivePairModulus 75 (a j : ℝ) s) →
        h158PhasePotential (fun j => (a j : ℝ)) (h158PhaseCeilingTheta n i.val) s ≤
          h158PhaseCeiling (h158PhaseCeilingTheta n i.val)+1 := by
  refine ⟨h158PhaseSelectedRoots (h158PhaseCeilingTheta n i.val), ?_, ?_⟩
  · intro j
    exact ⟨(h158PhaseSelectedRoots_bounds _ j).1.le, (h158PhaseSelectedRoots_bounds _ j).2.le⟩
  · intro s hs0 hs96 hp
    exact h158CompactPhase_selected_le_add_one
      (h158PhaseCeilingTheta_mem n i.val (by omega) i.isLt) ⟨hs0, hs96⟩ hp

end OddZetaMixed
