-- Generated by generate_compact_phase.py from exact rational arithmetic.
import OddZetaMixed.H158CompactPhase
import OddZetaMixed.RationalLogBounds
import OddZetaMixed.RationalArctanBounds

noncomputable section
set_option maxRecDepth 100000
set_option maxHeartbeats 0
namespace OddZetaMixed.CompactPhase.Certificates
open Finset

def piE : Enclosure Real.pi :=
  ⟨RationalArctanBounds.piLower, RationalArctanBounds.piUpper,
    RationalArctanBounds.pi_sound.1, RationalArctanBounds.pi_sound.2⟩

def log_0 : Enclosure (Real.log (52 : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded 52 (5) 12 1000000000000
    (7902487437/2000000000) (39512437187/10000000000) (by decide +kernel)
  exact ⟨(7902487437/2000000000), (39512437187/10000000000), h.1, h.2⟩

def log_1 : Enclosure (Real.log (50 : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded 50 (5) 12 1000000000000
    (39120230053/10000000000) (4890028757/1250000000) (by decide +kernel)
  exact ⟨(39120230053/10000000000), (4890028757/1250000000), h.1, h.2⟩

def log_2 : Enclosure (Real.log (48 : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded 48 (5) 12 1000000000000
    (9678002527/2500000000) (38712010111/10000000000) (by decide +kernel)
  exact ⟨(9678002527/2500000000), (38712010111/10000000000), h.1, h.2⟩

def log_3 : Enclosure (Real.log (46 : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded 46 (5) 12 1000000000000
    (9571603491/2500000000) (19143206983/5000000000) (by decide +kernel)
  exact ⟨(9571603491/2500000000), (19143206983/5000000000), h.1, h.2⟩

def log_4 : Enclosure (Real.log (44 : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded 44 (5) 12 1000000000000
    (18920948169/5000000000) (37841896341/10000000000) (by decide +kernel)
  exact ⟨(18920948169/5000000000), (37841896341/10000000000), h.1, h.2⟩

def log_5 : Enclosure (Real.log (42 : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded 42 (5) 12 1000000000000
    (18688348091/5000000000) (4672087023/1250000000) (by decide +kernel)
  exact ⟨(18688348091/5000000000), (4672087023/1250000000), h.1, h.2⟩

def log_6 : Enclosure (Real.log (40 : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded 40 (5) 12 1000000000000
    (1844439727/500000000) (36888794543/10000000000) (by decide +kernel)
  exact ⟨(1844439727/500000000), (36888794543/10000000000), h.1, h.2⟩

def log_7 : Enclosure (Real.log (38 : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded 38 (5) 12 1000000000000
    (9093965399/2500000000) (36375861599/10000000000) (by decide +kernel)
  exact ⟨(9093965399/2500000000), (36375861599/10000000000), h.1, h.2⟩

def log_8 : Enclosure (Real.log (36 : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded 36 (5) 12 1000000000000
    (4479398673/1250000000) (17917594693/5000000000) (by decide +kernel)
  exact ⟨(4479398673/1250000000), (17917594693/5000000000), h.1, h.2⟩

def log_9 : Enclosure (Real.log (34 : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded 34 (5) 12 1000000000000
    (7052721049/2000000000) (68874229/19531250) (by decide +kernel)
  exact ⟨(7052721049/2000000000), (68874229/19531250), h.1, h.2⟩

def log_10 : Enclosure (Real.log (32 : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded 32 (5) 12 1000000000000
    (34657359027/10000000000) (34657359029/10000000000) (by decide +kernel)
  exact ⟨(34657359027/10000000000), (34657359029/10000000000), h.1, h.2⟩

def log_11 : Enclosure (Real.log (30 : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded 30 (4) 12 1000000000000
    (4251496727/1250000000) (17005986909/5000000000) (by decide +kernel)
  exact ⟨(4251496727/1250000000), (17005986909/5000000000), h.1, h.2⟩

def log_12 : Enclosure (Real.log (28 : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded 28 (4) 12 1000000000000
    (33322045101/10000000000) (33322045103/10000000000) (by decide +kernel)
  exact ⟨(33322045101/10000000000), (33322045103/10000000000), h.1, h.2⟩

def log_13 : Enclosure (Real.log (26 : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded 26 (4) 12 1000000000000
    (32580965379/10000000000) (16290482691/5000000000) (by decide +kernel)
  exact ⟨(32580965379/10000000000), (16290482691/5000000000), h.1, h.2⟩

def log_14 : Enclosure (Real.log (24 : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded 24 (4) 12 1000000000000
    (31780538303/10000000000) (6356107661/2000000000) (by decide +kernel)
  exact ⟨(31780538303/10000000000), (6356107661/2000000000), h.1, h.2⟩

def log_15 : Enclosure (Real.log (22 : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded 22 (4) 12 1000000000000
    (30910424533/10000000000) (6182084907/2000000000) (by decide +kernel)
  exact ⟨(30910424533/10000000000), (6182084907/2000000000), h.1, h.2⟩

def log_16 : Enclosure (Real.log (49 : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded 49 (5) 12 1000000000000
    (1945910149/500000000) (38918202983/10000000000) (by decide +kernel)
  exact ⟨(1945910149/500000000), (38918202983/10000000000), h.1, h.2⟩

def log_17 : Enclosure (Real.log (51 : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded 51 (5) 12 1000000000000
    (19659128163/5000000000) (39318256329/10000000000) (by decide +kernel)
  exact ⟨(19659128163/5000000000), (39318256329/10000000000), h.1, h.2⟩

def constantLogs : ∀ i, Enclosure (Real.log (constantArg i : ℝ)) := by
  refine Fin.cases ?_ ?_
  · exact log_0.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_1.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_2.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_3.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_4.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_5.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_6.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_7.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_8.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_9.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_10.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_11.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_12.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_13.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_14.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_15.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_2.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_16.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_1.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_17.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_0.ofRatEq (by decide +kernel)
  exact fun i => Fin.elim0 i

def constantE := constantEnclosure constantLogs

#check constantE

def log_18 : Enclosure (Real.log ((94873/4) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (94873/4) (14) 12 1000000000000
    (12592500091/1250000000) (100740000733/10000000000) (by decide +kernel)
  exact ⟨(12592500091/1250000000), (100740000733/10000000000), h.1, h.2⟩

def log_19 : Enclosure (Real.log ((73/4) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (73/4) (4) 12 1000000000000
    (29041650799/10000000000) (14520825401/5000000000) (by decide +kernel)
  exact ⟨(29041650799/10000000000), (14520825401/5000000000), h.1, h.2⟩

def log_20 : Enclosure (Real.log ((7753/4) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (7753/4) (10) 12 1000000000000
    (75695407829/10000000000) (75695407833/10000000000) (by decide +kernel)
  exact ⟨(75695407829/10000000000), (75695407833/10000000000), h.1, h.2⟩

def log_21 : Enclosure (Real.log ((8109/4) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (8109/4) (10) 12 1000000000000
    (76144354737/10000000000) (76144354741/10000000000) (by decide +kernel)
  exact ⟨(76144354737/10000000000), (76144354741/10000000000), h.1, h.2⟩

def log_22 : Enclosure (Real.log ((8473/4) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (8473/4) (11) 12 1000000000000
    (76583455549/10000000000) (76583455553/10000000000) (by decide +kernel)
  exact ⟨(76583455549/10000000000), (76583455553/10000000000), h.1, h.2⟩

def log_23 : Enclosure (Real.log ((8845/4) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (8845/4) (11) 12 1000000000000
    (77013132453/10000000000) (77013132457/10000000000) (by decide +kernel)
  exact ⟨(77013132453/10000000000), (77013132457/10000000000), h.1, h.2⟩

def log_24 : Enclosure (Real.log ((9225/4) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (9225/4) (11) 12 1000000000000
    (19358445269/2500000000) (1935844527/250000000) (by decide +kernel)
  exact ⟨(19358445269/2500000000), (1935844527/250000000), h.1, h.2⟩

def log_25 : Enclosure (Real.log ((9613/4) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (9613/4) (11) 12 1000000000000
    (19461443167/2500000000) (608170099/78125000) (by decide +kernel)
  exact ⟨(19461443167/2500000000), (608170099/78125000), h.1, h.2⟩

def log_26 : Enclosure (Real.log ((10009/4) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (10009/4) (11) 12 1000000000000
    (78249456059/10000000000) (1222647751/156250000) (by decide +kernel)
  exact ⟨(78249456059/10000000000), (1222647751/156250000), h.1, h.2⟩

def log_27 : Enclosure (Real.log ((10413/4) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (10413/4) (11) 12 1000000000000
    (9830644929/1250000000) (78645159437/10000000000) (by decide +kernel)
  exact ⟨(9830644929/1250000000), (78645159437/10000000000), h.1, h.2⟩

def log_28 : Enclosure (Real.log ((10825/4) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (10825/4) (11) 12 1000000000000
    (19758297979/2500000000) (987914899/125000000) (by decide +kernel)
  exact ⟨(19758297979/2500000000), (987914899/125000000), h.1, h.2⟩

def log_29 : Enclosure (Real.log ((11245/4) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (11245/4) (11) 12 1000000000000
    (79413845031/10000000000) (15882769007/2000000000) (by decide +kernel)
  exact ⟨(79413845031/10000000000), (15882769007/2000000000), h.1, h.2⟩

def log_30 : Enclosure (Real.log ((11673/4) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (11673/4) (11) 12 1000000000000
    (19946848501/2500000000) (9973424251/1250000000) (by decide +kernel)
  exact ⟨(19946848501/2500000000), (9973424251/1250000000), h.1, h.2⟩

def log_31 : Enclosure (Real.log ((12109/4) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (12109/4) (11) 12 1000000000000
    (16030819791/2000000000) (80154098959/10000000000) (by decide +kernel)
  exact ⟨(16030819791/2000000000), (80154098959/10000000000), h.1, h.2⟩

def log_32 : Enclosure (Real.log ((12553/4) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (12553/4) (11) 12 1000000000000
    (16102841197/2000000000) (8051420599/1000000000) (by decide +kernel)
  exact ⟨(16102841197/2000000000), (8051420599/1000000000), h.1, h.2⟩

def log_33 : Enclosure (Real.log ((13005/4) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (13005/4) (11) 12 1000000000000
    (40433974083/5000000000) (8086794817/1000000000) (by decide +kernel)
  exact ⟨(40433974083/5000000000), (8086794817/1000000000), h.1, h.2⟩

def log_34 : Enclosure (Real.log ((13465/4) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (13465/4) (11) 12 1000000000000
    (2030388661/250000000) (20303886611/2500000000) (by decide +kernel)
  exact ⟨(2030388661/250000000), (20303886611/2500000000), h.1, h.2⟩

def log_35 : Enclosure (Real.log ((13933/4) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (13933/4) (11) 12 1000000000000
    (5097325653/625000000) (20389302613/2500000000) (by decide +kernel)
  exact ⟨(5097325653/625000000), (20389302613/2500000000), h.1, h.2⟩

def log_36 : Enclosure (Real.log ((14409/4) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (14409/4) (11) 12 1000000000000
    (8189313929/1000000000) (16378627859/2000000000) (by decide +kernel)
  exact ⟨(8189313929/1000000000), (16378627859/2000000000), h.1, h.2⟩

def log_37 : Enclosure (Real.log ((14893/4) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (14893/4) (11) 12 1000000000000
    (10277940277/1250000000) (4111176111/500000000) (by decide +kernel)
  exact ⟨(10277940277/1250000000), (4111176111/500000000), h.1, h.2⟩

def log_38 : Enclosure (Real.log ((15385/4) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (15385/4) (11) 12 1000000000000
    (16509707853/2000000000) (82548539269/10000000000) (by decide +kernel)
  exact ⟨(16509707853/2000000000), (82548539269/10000000000), h.1, h.2⟩

def log_39 : Enclosure (Real.log ((15885/4) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (15885/4) (11) 12 1000000000000
    (41434180927/5000000000) (41434180929/5000000000) (by decide +kernel)
  exact ⟨(41434180927/5000000000), (41434180929/5000000000), h.1, h.2⟩

def log_40 : Enclosure (Real.log ((16393/4) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (16393/4) (12) 12 1000000000000
    (83183153321/10000000000) (41591576663/5000000000) (by decide +kernel)
  exact ⟨(83183153321/10000000000), (41591576663/5000000000), h.1, h.2⟩

def log_41 : Enclosure (Real.log ((44953/4) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (44953/4) (13) 12 1000000000000
    (23317696043/2500000000) (93270784177/10000000000) (by decide +kernel)
  exact ⟨(23317696043/2500000000), (93270784177/10000000000), h.1, h.2⟩

def log_42 : Enclosure (Real.log ((44109/4) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (44109/4) (13) 12 1000000000000
    (93081247609/10000000000) (46540623807/5000000000) (by decide +kernel)
  exact ⟨(93081247609/10000000000), (46540623807/5000000000), h.1, h.2⟩

def log_43 : Enclosure (Real.log ((43273/4) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (43273/4) (13) 12 1000000000000
    (2902809313/312500000) (92889898021/10000000000) (by decide +kernel)
  exact ⟨(2902809313/312500000), (92889898021/10000000000), h.1, h.2⟩

def log_44 : Enclosure (Real.log ((42445/4) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (42445/4) (13) 12 1000000000000
    (92696700379/10000000000) (92696700383/10000000000) (by decide +kernel)
  exact ⟨(92696700379/10000000000), (92696700383/10000000000), h.1, h.2⟩

def log_45 : Enclosure (Real.log ((41625/4) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (41625/4) (13) 12 1000000000000
    (4625080933/500000000) (18500323733/2000000000) (by decide +kernel)
  exact ⟨(4625080933/500000000), (18500323733/2000000000), h.1, h.2⟩

def log_46 : Enclosure (Real.log ((40813/4) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (40813/4) (13) 12 1000000000000
    (46152307879/5000000000) (92304615763/10000000000) (by decide +kernel)
  exact ⟨(46152307879/5000000000), (92304615763/10000000000), h.1, h.2⟩

def log_47 : Enclosure (Real.log ((40009/4) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (40009/4) (13) 12 1000000000000
    (18421130693/2000000000) (9210565347/1000000000) (by decide +kernel)
  exact ⟨(18421130693/2000000000), (9210565347/1000000000), h.1, h.2⟩

def log_48 : Enclosure (Real.log ((39213/4) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (39213/4) (13) 12 1000000000000
    (91904692421/10000000000) (45952346213/5000000000) (by decide +kernel)
  exact ⟨(91904692421/10000000000), (45952346213/5000000000), h.1, h.2⟩

def log_49 : Enclosure (Real.log ((38425/4) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (38425/4) (13) 12 1000000000000
    (91701692071/10000000000) (22925423019/2500000000) (by decide +kernel)
  exact ⟨(91701692071/10000000000), (22925423019/2500000000), h.1, h.2⟩

def log_50 : Enclosure (Real.log ((37645/4) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (37645/4) (13) 12 1000000000000
    (9149661061/1000000000) (18299322123/2000000000) (by decide +kernel)
  exact ⟨(9149661061/1000000000), (18299322123/2000000000), h.1, h.2⟩

def log_51 : Enclosure (Real.log ((36873/4) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (36873/4) (13) 12 1000000000000
    (11411175617/1250000000) (91289404941/10000000000) (by decide +kernel)
  exact ⟨(11411175617/1250000000), (91289404941/10000000000), h.1, h.2⟩

def log_52 : Enclosure (Real.log ((36109/4) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (36109/4) (13) 12 1000000000000
    (45540015297/5000000000) (91080030599/10000000000) (by decide +kernel)
  exact ⟨(45540015297/5000000000), (91080030599/10000000000), h.1, h.2⟩

def log_53 : Enclosure (Real.log ((35353/4) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (35353/4) (13) 12 1000000000000
    (90868441721/10000000000) (3634737669/400000000) (by decide +kernel)
  exact ⟨(90868441721/10000000000), (3634737669/400000000), h.1, h.2⟩

def log_54 : Enclosure (Real.log ((34605/4) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (34605/4) (13) 12 1000000000000
    (4532729549/500000000) (11331823873/1250000000) (by decide +kernel)
  exact ⟨(4532729549/500000000), (11331823873/1250000000), h.1, h.2⟩

def log_55 : Enclosure (Real.log ((33865/4) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (33865/4) (13) 12 1000000000000
    (90438429503/10000000000) (22609607377/2500000000) (by decide +kernel)
  exact ⟨(90438429503/10000000000), (22609607377/2500000000), h.1, h.2⟩

def log_56 : Enclosure (Real.log ((33133/4) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (33133/4) (13) 12 1000000000000
    (90219906823/10000000000) (90219906827/10000000000) (by decide +kernel)
  exact ⟨(90219906823/10000000000), (90219906827/10000000000), h.1, h.2⟩

def log_57 : Enclosure (Real.log ((32409/4) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (32409/4) (12) 12 1000000000000
    (89998970797/10000000000) (89998970801/10000000000) (by decide +kernel)
  exact ⟨(89998970797/10000000000), (89998970801/10000000000), h.1, h.2⟩

def log_58 : Enclosure (Real.log ((31693/4) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (31693/4) (12) 12 1000000000000
    (4488778377/500000000) (11221945943/1250000000) (by decide +kernel)
  exact ⟨(4488778377/500000000), (11221945943/1250000000), h.1, h.2⟩

def log_59 : Enclosure (Real.log ((30985/4) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (30985/4) (12) 12 1000000000000
    (89549641341/10000000000) (17909928269/2000000000) (by decide +kernel)
  exact ⟨(89549641341/10000000000), (17909928269/2000000000), h.1, h.2⟩

def log_60 : Enclosure (Real.log ((30285/4) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (30285/4) (12) 12 1000000000000
    (89321134581/10000000000) (44660567293/5000000000) (by decide +kernel)
  exact ⟨(89321134581/10000000000), (44660567293/5000000000), h.1, h.2⟩

def log_61 : Enclosure (Real.log ((29593/4) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (29593/4) (12) 12 1000000000000
    (44544993823/5000000000) (1781799753/200000000) (by decide +kernel)
  exact ⟨(44544993823/5000000000), (1781799753/200000000), h.1, h.2⟩

def atan_0 : Enclosure (Real.arctan ((3/308) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/308) 10
    (97399517/10000000000) (48699759/5000000000) (by decide +kernel)
  exact ⟨(97399517/10000000000), (48699759/5000000000), h.1, h.2⟩

def atan_1 : Enclosure (Real.arctan ((3/8) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/8) 10
    (1793853351/5000000000) (3587706703/10000000000) (by decide +kernel)
  exact ⟨(1793853351/5000000000), (3587706703/10000000000), h.1, h.2⟩

def atan_2 : Enclosure (Real.arctan ((3/88) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/88) 10
    (68155423/2000000000) (85194279/2500000000) (by decide +kernel)
  exact ⟨(68155423/2000000000), (85194279/2500000000), h.1, h.2⟩

def atan_3 : Enclosure (Real.arctan ((1/30) : ℚ)) := by
  have h := RationalArctanBounds.of_check (1/30) 10
    (166604979/5000000000) (333209959/10000000000) (by decide +kernel)
  exact ⟨(166604979/5000000000), (333209959/10000000000), h.1, h.2⟩

def atan_4 : Enclosure (Real.arctan ((3/92) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/92) 10
    (325971451/10000000000) (81492863/2500000000) (by decide +kernel)
  exact ⟨(325971451/10000000000), (81492863/2500000000), h.1, h.2⟩

def atan_5 : Enclosure (Real.arctan ((3/94) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/94) 10
    (79760161/2500000000) (63808129/2000000000) (by decide +kernel)
  exact ⟨(79760161/2500000000), (63808129/2000000000), h.1, h.2⟩

def atan_6 : Enclosure (Real.arctan ((1/32) : ℚ)) := by
  have h := RationalArctanBounds.of_check (1/32) 10
    (156199167/5000000000) (62479667/2000000000) (by decide +kernel)
  exact ⟨(156199167/5000000000), (62479667/2000000000), h.1, h.2⟩

def atan_7 : Enclosure (Real.arctan ((3/98) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/98) 10
    (306026879/10000000000) (478167/15625000) (by decide +kernel)
  exact ⟨(306026879/10000000000), (478167/15625000), h.1, h.2⟩

def atan_8 : Enclosure (Real.arctan ((3/100) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/100) 10
    (9372189/312500000) (299910049/10000000000) (by decide +kernel)
  exact ⟨(9372189/312500000), (299910049/10000000000), h.1, h.2⟩

def atan_9 : Enclosure (Real.arctan ((1/34) : ℚ)) := by
  have h := RationalArctanBounds.of_check (1/34) 10
    (147016441/5000000000) (294032883/10000000000) (by decide +kernel)
  exact ⟨(147016441/5000000000), (294032883/10000000000), h.1, h.2⟩

def atan_10 : Enclosure (Real.arctan ((3/104) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/104) 10
    (2252981/78125000) (288381569/10000000000) (by decide +kernel)
  exact ⟨(2252981/78125000), (288381569/10000000000), h.1, h.2⟩

def atan_11 : Enclosure (Real.arctan ((3/106) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/106) 10
    (141471669/5000000000) (282943339/10000000000) (by decide +kernel)
  exact ⟨(141471669/5000000000), (282943339/10000000000), h.1, h.2⟩

def atan_12 : Enclosure (Real.arctan ((1/36) : ℚ)) := by
  have h := RationalArctanBounds.of_check (1/36) 10
    (55541273/2000000000) (138853183/5000000000) (by decide +kernel)
  exact ⟨(55541273/2000000000), (138853183/5000000000), h.1, h.2⟩

def atan_13 : Enclosure (Real.arctan ((3/110) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/110) 10
    (68164921/2500000000) (54531937/2000000000) (by decide +kernel)
  exact ⟨(68164921/2500000000), (54531937/2000000000), h.1, h.2⟩

def atan_14 : Enclosure (Real.arctan ((3/112) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/112) 10
    (26779311/1000000000) (267793111/10000000000) (by decide +kernel)
  exact ⟨(26779311/1000000000), (267793111/10000000000), h.1, h.2⟩

def atan_15 : Enclosure (Real.arctan ((1/38) : ℚ)) := by
  have h := RationalArctanBounds.of_check (1/38) 10
    (65774293/2500000000) (263097173/10000000000) (by decide +kernel)
  exact ⟨(65774293/2500000000), (263097173/10000000000), h.1, h.2⟩

def atan_16 : Enclosure (Real.arctan ((3/116) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/116) 10
    (258563053/10000000000) (129281527/5000000000) (by decide +kernel)
  exact ⟨(258563053/10000000000), (129281527/5000000000), h.1, h.2⟩

def atan_17 : Enclosure (Real.arctan ((3/118) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/118) 10
    (63545633/2500000000) (254182533/10000000000) (by decide +kernel)
  exact ⟨(63545633/2500000000), (254182533/10000000000), h.1, h.2⟩

def atan_18 : Enclosure (Real.arctan ((1/40) : ℚ)) := by
  have h := RationalArctanBounds.of_check (1/40) 10
    (7810873/312500000) (249947937/10000000000) (by decide +kernel)
  exact ⟨(7810873/312500000), (249947937/10000000000), h.1, h.2⟩

def atan_19 : Enclosure (Real.arctan ((3/122) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/122) 10
    (245852093/10000000000) (122926047/5000000000) (by decide +kernel)
  exact ⟨(245852093/10000000000), (122926047/5000000000), h.1, h.2⟩

def atan_20 : Enclosure (Real.arctan ((3/124) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/124) 10
    (30236037/1250000000) (241888297/10000000000) (by decide +kernel)
  exact ⟨(30236037/1250000000), (241888297/10000000000), h.1, h.2⟩

def atan_21 : Enclosure (Real.arctan ((1/42) : ℚ)) := by
  have h := RationalArctanBounds.of_check (1/42) 10
    (238050261/10000000000) (119025131/5000000000) (by decide +kernel)
  exact ⟨(238050261/10000000000), (119025131/5000000000), h.1, h.2⟩

def atan_22 : Enclosure (Real.arctan ((3/128) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/128) 10
    (117166049/5000000000) (234332099/10000000000) (by decide +kernel)
  exact ⟨(117166049/5000000000), (234332099/10000000000), h.1, h.2⟩

def atan_23 : Enclosure (Real.arctan ((3/212) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/212) 10
    (141499989/10000000000) (14149999/1000000000) (by decide +kernel)
  exact ⟨(141499989/10000000000), (14149999/1000000000), h.1, h.2⟩

def atan_24 : Enclosure (Real.arctan ((1/70) : ℚ)) := by
  have h := RationalArctanBounds.of_check (1/70) 10
    (5713897/400000000) (71423713/5000000000) (by decide +kernel)
  exact ⟨(5713897/400000000), (71423713/5000000000), h.1, h.2⟩

def atan_25 : Enclosure (Real.arctan ((3/208) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/208) 10
    (144220769/10000000000) (14422077/1000000000) (by decide +kernel)
  exact ⟨(144220769/10000000000), (14422077/1000000000), h.1, h.2⟩

def atan_26 : Enclosure (Real.arctan ((3/206) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/206) 10
    (145620773/10000000000) (72810387/5000000000) (by decide +kernel)
  exact ⟨(145620773/10000000000), (72810387/5000000000), h.1, h.2⟩

def atan_27 : Enclosure (Real.arctan ((1/68) : ℚ)) := by
  have h := RationalArctanBounds.of_check (1/68) 10
    (147048223/10000000000) (4595257/312500000) (by decide +kernel)
  exact ⟨(147048223/10000000000), (4595257/312500000), h.1, h.2⟩

def atan_28 : Enclosure (Real.arctan ((3/202) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/202) 10
    (148503933/10000000000) (74251967/5000000000) (by decide +kernel)
  exact ⟨(148503933/10000000000), (74251967/5000000000), h.1, h.2⟩

def atan_29 : Enclosure (Real.arctan ((3/200) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/200) 10
    (149988751/10000000000) (9374297/625000000) (by decide +kernel)
  exact ⟨(149988751/10000000000), (9374297/625000000), h.1, h.2⟩

def atan_30 : Enclosure (Real.arctan ((1/66) : ℚ)) := by
  have h := RationalArctanBounds.of_check (1/66) 10
    (75751779/5000000000) (151503559/10000000000) (by decide +kernel)
  exact ⟨(75751779/5000000000), (151503559/10000000000), h.1, h.2⟩

def atan_31 : Enclosure (Real.arctan ((3/196) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/196) 10
    (153049273/10000000000) (76524637/5000000000) (by decide +kernel)
  exact ⟨(153049273/10000000000), (76524637/5000000000), h.1, h.2⟩

def atan_32 : Enclosure (Real.arctan ((3/194) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/194) 10
    (3092537/200000000) (154626851/10000000000) (by decide +kernel)
  exact ⟨(3092537/200000000), (154626851/10000000000), h.1, h.2⟩

def atan_33 : Enclosure (Real.arctan ((1/64) : ℚ)) := by
  have h := RationalArctanBounds.of_check (1/64) 10
    (78118643/5000000000) (156237287/10000000000) (by decide +kernel)
  exact ⟨(78118643/5000000000), (156237287/10000000000), h.1, h.2⟩

def atan_34 : Enclosure (Real.arctan ((3/190) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/190) 10
    (157881617/10000000000) (78940809/5000000000) (by decide +kernel)
  exact ⟨(157881617/10000000000), (78940809/5000000000), h.1, h.2⟩

def atan_35 : Enclosure (Real.arctan ((3/188) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/188) 10
    (6382437/400000000) (79780463/5000000000) (by decide +kernel)
  exact ⟨(6382437/400000000), (79780463/5000000000), h.1, h.2⟩

def atan_36 : Enclosure (Real.arctan ((1/62) : ℚ)) := by
  have h := RationalArctanBounds.of_check (1/62) 10
    (80638169/5000000000) (161276339/10000000000) (by decide +kernel)
  exact ⟨(80638169/5000000000), (161276339/10000000000), h.1, h.2⟩

def atan_37 : Enclosure (Real.arctan ((3/184) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/184) 10
    (163029033/10000000000) (81514517/5000000000) (by decide +kernel)
  exact ⟨(163029033/10000000000), (81514517/5000000000), h.1, h.2⟩

def atan_38 : Enclosure (Real.arctan ((3/182) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/182) 10
    (82410119/5000000000) (164820239/10000000000) (by decide +kernel)
  exact ⟨(82410119/5000000000), (164820239/10000000000), h.1, h.2⟩

def atan_39 : Enclosure (Real.arctan ((1/60) : ℚ)) := by
  have h := RationalArctanBounds.of_check (1/60) 10
    (166651237/10000000000) (83325619/5000000000) (by decide +kernel)
  exact ⟨(166651237/10000000000), (83325619/5000000000), h.1, h.2⟩

def atan_40 : Enclosure (Real.arctan ((3/178) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/178) 10
    (16852337/1000000000) (168523371/10000000000) (by decide +kernel)
  exact ⟨(16852337/1000000000), (168523371/10000000000), h.1, h.2⟩

def atan_41 : Enclosure (Real.arctan ((3/176) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/176) 10
    (170438039/10000000000) (4260951/250000000) (by decide +kernel)
  exact ⟨(170438039/10000000000), (4260951/250000000), h.1, h.2⟩

def atan_42 : Enclosure (Real.arctan ((1/58) : ℚ)) := by
  have h := RationalArctanBounds.of_check (1/58) 10
    (172396711/10000000000) (21549589/1250000000) (by decide +kernel)
  exact ⟨(172396711/10000000000), (21549589/1250000000), h.1, h.2⟩

def atan_43 : Enclosure (Real.arctan ((3/172) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/172) 10
    (4360023/250000000) (174400921/10000000000) (by decide +kernel)
  exact ⟨(4360023/250000000), (174400921/10000000000), h.1, h.2⟩

def atan_44 : Enclosure (Real.arctan (0 : ℚ)) := by
  have h := RationalArctanBounds.of_check 0 10
    0 0 (by decide +kernel)
  exact ⟨0, 0, h.1, h.2⟩

def atan_45 : Enclosure (Real.arctan ((3/154) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/154) 10
    (97390279/5000000000) (194780559/10000000000) (by decide +kernel)
  exact ⟨(97390279/5000000000), (194780559/10000000000), h.1, h.2⟩

def atan_46 : Enclosure (Real.arctan ((3/4) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/4) 10
    (6435011087/10000000000) (402188193/625000000) (by decide +kernel)
  exact ⟨(6435011087/10000000000), (402188193/625000000), h.1, h.2⟩

def atan_47 : Enclosure (Real.arctan ((3/44) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/44) 10
    (340382291/5000000000) (680764583/10000000000) (by decide +kernel)
  exact ⟨(340382291/5000000000), (680764583/10000000000), h.1, h.2⟩

def atan_48 : Enclosure (Real.arctan ((1/15) : ℚ)) := by
  have h := RationalArctanBounds.of_check (1/15) 10
    (665681637/10000000000) (332840819/5000000000) (by decide +kernel)
  exact ⟨(665681637/10000000000), (332840819/5000000000), h.1, h.2⟩

def atan_49 : Enclosure (Real.arctan ((3/46) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/46) 10
    (651251633/10000000000) (325625817/5000000000) (by decide +kernel)
  exact ⟨(651251633/10000000000), (325625817/5000000000), h.1, h.2⟩

def atan_50 : Enclosure (Real.arctan ((3/47) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/47) 10
    (1019893/16000000) (318716563/5000000000) (by decide +kernel)
  exact ⟨(1019893/16000000), (318716563/5000000000), h.1, h.2⟩

def atan_51 : Enclosure (Real.arctan ((1/16) : ℚ)) := by
  have h := RationalArctanBounds.of_check (1/16) 10
    (624188099/10000000000) (6241881/100000000) (by decide +kernel)
  exact ⟨(624188099/10000000000), (6241881/100000000), h.1, h.2⟩

def atan_52 : Enclosure (Real.arctan ((3/49) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/49) 10
    (305740813/5000000000) (611481627/10000000000) (by decide +kernel)
  exact ⟨(305740813/5000000000), (611481627/10000000000), h.1, h.2⟩

def atan_53 : Enclosure (Real.arctan ((3/50) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/50) 10
    (599281551/10000000000) (37455097/625000000) (by decide +kernel)
  exact ⟨(599281551/10000000000), (37455097/625000000), h.1, h.2⟩

def atan_54 : Enclosure (Real.arctan ((1/17) : ℚ)) := by
  have h := RationalArctanBounds.of_check (1/17) 10
    (587558227/10000000000) (146889557/2500000000) (by decide +kernel)
  exact ⟨(587558227/10000000000), (146889557/2500000000), h.1, h.2⟩

def atan_55 : Enclosure (Real.arctan ((3/52) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/52) 10
    (288142137/5000000000) (23051371/400000000) (by decide +kernel)
  exact ⟨(288142137/5000000000), (23051371/400000000), h.1, h.2⟩

def atan_56 : Enclosure (Real.arctan ((3/53) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/53) 10
    (565434369/10000000000) (56543437/1000000000) (by decide +kernel)
  exact ⟨(565434369/10000000000), (56543437/1000000000), h.1, h.2⟩

def atan_57 : Enclosure (Real.arctan ((1/18) : ℚ)) := by
  have h := RationalArctanBounds.of_check (1/18) 10
    (138746263/2500000000) (554985053/10000000000) (by decide +kernel)
  exact ⟨(138746263/2500000000), (554985053/10000000000), h.1, h.2⟩

def atan_58 : Enclosure (Real.arctan ((3/55) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/55) 10
    (272457281/5000000000) (544914563/10000000000) (by decide +kernel)
  exact ⟨(272457281/5000000000), (544914563/10000000000), h.1, h.2⟩

def atan_59 : Enclosure (Real.arctan ((3/56) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/56) 10
    (133800671/2500000000) (107040537/2000000000) (by decide +kernel)
  exact ⟨(133800671/2500000000), (107040537/2000000000), h.1, h.2⟩

def atan_60 : Enclosure (Real.arctan ((1/19) : ℚ)) := by
  have h := RationalArctanBounds.of_check (1/19) 10
    (65728827/1250000000) (525830617/10000000000) (by decide +kernel)
  exact ⟨(65728827/1250000000), (525830617/10000000000), h.1, h.2⟩

def atan_61 : Enclosure (Real.arctan ((3/58) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/58) 10
    (129195211/2500000000) (103356169/2000000000) (by decide +kernel)
  exact ⟨(129195211/2500000000), (103356169/2000000000), h.1, h.2⟩

def atan_62 : Enclosure (Real.arctan ((3/59) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/59) 10
    (6350463/125000000) (508037041/10000000000) (by decide +kernel)
  exact ⟨(6350463/125000000), (508037041/10000000000), h.1, h.2⟩

def atan_63 : Enclosure (Real.arctan ((1/20) : ℚ)) := by
  have h := RationalArctanBounds.of_check (1/20) 10
    (499583957/10000000000) (249791979/5000000000) (by decide +kernel)
  exact ⟨(499583957/10000000000), (249791979/5000000000), h.1, h.2⟩

def atan_64 : Enclosure (Real.arctan ((3/61) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/61) 10
    (30712959/625000000) (98281469/2000000000) (by decide +kernel)
  exact ⟨(30712959/625000000), (98281469/2000000000), h.1, h.2⟩

def atan_65 : Enclosure (Real.arctan ((3/62) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/62) 10
    (241746933/5000000000) (483493867/10000000000) (by decide +kernel)
  exact ⟨(241746933/5000000000), (483493867/10000000000), h.1, h.2⟩

def atan_66 : Enclosure (Real.arctan ((1/21) : ℚ)) := by
  have h := RationalArctanBounds.of_check (1/21) 10
    (59478879/1250000000) (475831033/10000000000) (by decide +kernel)
  exact ⟨(59478879/1250000000), (475831033/10000000000), h.1, h.2⟩

def atan_67 : Enclosure (Real.arctan ((3/64) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/64) 10
    (468407129/10000000000) (46840713/1000000000) (by decide +kernel)
  exact ⟨(468407129/10000000000), (46840713/1000000000), h.1, h.2⟩

def atan_68 : Enclosure (Real.arctan ((1/35) : ℚ)) := by
  have h := RationalArctanBounds.of_check (1/35) 10
    (142818289/5000000000) (285636579/10000000000) (by decide +kernel)
  exact ⟨(142818289/5000000000), (285636579/10000000000), h.1, h.2⟩

def atan_69 : Enclosure (Real.arctan ((3/103) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/103) 10
    (58235963/2000000000) (36397477/1250000000) (by decide +kernel)
  exact ⟨(58235963/2000000000), (36397477/1250000000), h.1, h.2⟩

def atan_70 : Enclosure (Real.arctan ((3/101) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/101) 10
    (74235599/2500000000) (296942397/10000000000) (by decide +kernel)
  exact ⟨(74235599/2500000000), (296942397/10000000000), h.1, h.2⟩

def atan_71 : Enclosure (Real.arctan ((1/33) : ℚ)) := by
  have h := RationalArctanBounds.of_check (1/33) 10
    (302937599/10000000000) (23667/781250) (by decide +kernel)
  exact ⟨(302937599/10000000000), (23667/781250), h.1, h.2⟩

def atan_72 : Enclosure (Real.arctan ((3/97) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/97) 10
    (61835959/2000000000) (77294949/2500000000) (by decide +kernel)
  exact ⟨(61835959/2000000000), (77294949/2500000000), h.1, h.2⟩

def atan_73 : Enclosure (Real.arctan ((3/95) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/95) 10
    (78921141/2500000000) (63136913/2000000000) (by decide +kernel)
  exact ⟨(78921141/2500000000), (63136913/2000000000), h.1, h.2⟩

def atan_74 : Enclosure (Real.arctan ((1/31) : ℚ)) := by
  have h := RationalArctanBounds.of_check (1/31) 10
    (40308603/1250000000) (12898753/400000000) (by decide +kernel)
  exact ⟨(40308603/1250000000), (12898753/400000000), h.1, h.2⟩

def atan_75 : Enclosure (Real.arctan ((3/91) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/91) 10
    (2574617/78125000) (329550977/10000000000) (by decide +kernel)
  exact ⟨(2574617/78125000), (329550977/10000000000), h.1, h.2⟩

def atan_76 : Enclosure (Real.arctan ((3/89) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/89) 10
    (336951073/10000000000) (168475537/5000000000) (by decide +kernel)
  exact ⟨(336951073/10000000000), (168475537/5000000000), h.1, h.2⟩

def atan_77 : Enclosure (Real.arctan ((1/29) : ℚ)) := by
  have h := RationalArctanBounds.of_check (1/29) 10
    (344691009/10000000000) (34469101/1000000000) (by decide +kernel)
  exact ⟨(344691009/10000000000), (34469101/1000000000), h.1, h.2⟩

def atan_78 : Enclosure (Real.arctan ((3/86) : ℚ)) := by
  have h := RationalArctanBounds.of_check (3/86) 10
    (69739163/2000000000) (43586977/1250000000) (by decide +kernel)
  exact ⟨(69739163/2000000000), (43586977/1250000000), h.1, h.2⟩

def centerLogs : ∀ i, Enclosure (Real.log ((phaseArg i^2+((3/2) : ℚ)^2 : ℚ) : ℝ)) := by
  refine Fin.cases ?_ ?_
  · exact log_18.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_19.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_20.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_21.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_22.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_23.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_24.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_25.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_26.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_27.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_28.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_29.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_30.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_31.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_32.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_33.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_34.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_35.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_36.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_37.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_38.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_39.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_40.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_41.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_42.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_43.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_44.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_45.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_46.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_47.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_48.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_49.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_50.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_51.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_52.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_53.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_54.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_55.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_56.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_57.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_58.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_59.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_60.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_61.ofRatEq (by decide +kernel)
  exact fun i => Fin.elim0 i

def centerAtans : ∀ i, Enclosure (Real.arctan (((3/2)/phaseArg i : ℚ) : ℝ)) := by
  refine Fin.cases ?_ ?_
  · exact atan_0.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_1.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_2.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_3.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_4.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_5.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_6.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_7.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_8.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_9.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_10.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_11.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_12.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_13.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_14.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_15.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_16.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_17.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_18.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_19.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_20.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_21.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_22.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_23.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_24.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_25.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_26.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_27.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_28.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_29.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_30.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_31.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_32.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_33.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_34.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_35.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_36.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_37.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_38.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_39.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_40.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_41.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_42.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_43.ofRatEq (by decide +kernel)
  exact fun i => Fin.elim0 i

def leftAtans : ∀ i, Enclosure (Real.arctan ((0/phaseArg i : ℚ) : ℝ)) := by
  refine Fin.cases ?_ ?_
  · exact atan_44.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_44.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_44.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_44.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_44.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_44.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_44.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_44.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_44.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_44.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_44.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_44.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_44.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_44.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_44.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_44.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_44.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_44.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_44.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_44.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_44.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_44.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_44.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_44.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_44.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_44.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_44.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_44.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_44.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_44.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_44.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_44.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_44.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_44.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_44.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_44.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_44.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_44.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_44.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_44.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_44.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_44.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_44.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_44.ofRatEq (by decide +kernel)
  exact fun i => Fin.elim0 i

def rightAtans : ∀ i, Enclosure (Real.arctan ((3/phaseArg i : ℚ) : ℝ)) := by
  refine Fin.cases ?_ ?_
  · exact atan_45.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_46.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_47.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_48.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_49.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_50.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_51.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_52.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_53.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_54.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_55.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_56.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_57.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_58.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_59.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_60.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_61.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_62.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_63.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_64.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_65.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_66.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_67.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_11.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_68.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_10.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_69.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_9.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_70.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_8.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_71.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_7.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_72.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_6.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_73.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_5.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_74.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_4.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_75.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_3.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_76.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_2.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_77.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact atan_78.ofRatEq (by decide +kernel)
  exact fun i => Fin.elim0 i

def centerE := phaseEnclosure (3/2) constantE piE centerLogs centerAtans

#check centerE

theorem first_phase_cell {s : ℝ} (hs : 0 ≤ s ∧ s ≤ 3) : h158Phase s ≤ ((-2705260589693/5000000000) : ℚ) := by
  apply phase_enclosed_cell 0 3 (3/2) (10083439029/1000000000) (-2705260589693/5000000000)
    (by norm_num) (by norm_num) centerE piE leftAtans rightAtans
  · decide +kernel
  · decide +kernel
  · decide +kernel
  · simpa using hs

theorem endpoint_0_first_cell {s : ℝ} (hs : 0 ≤ s ∧ s ≤ 3) :
    h158PhasePotential (fun j => (h158PhaseRoots 0 j : ℝ)) 0 s ≤ ((-260611/500) : ℝ) := by
  apply potential_zero_cell_le
  exact (first_phase_cell hs).trans (by norm_num)

def log_62 : Enclosure (Real.log ((20279566947417246037746392752506383761/1000000000000000000000000) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (20279566947417246037746392752506383761/1000000000000000000000000) (44) 12 1000000000000
    (306406349403/10000000000) (38300793677/1250000000) (by decide +kernel)
  exact ⟨(306406349403/10000000000), (38300793677/1250000000), h.1, h.2⟩

def log_63 : Enclosure (Real.log ((346250834992042737176414061531841/15258789062500000000) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (346250834992042737176414061531841/15258789062500000000) (44) 12 1000000000000
    (61506057831/2000000000) (19220643073/625000000) (by decide +kernel)
  exact ⟨(61506057831/2000000000), (19220643073/625000000), h.1, h.2⟩

def log_64 : Enclosure (Real.log ((25123255676273407791417362350620279121/1000000000000000000000000) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (25123255676273407791417362350620279121/1000000000000000000000000) (44) 12 1000000000000
    (38568518817/1250000000) (308548150549/10000000000) (by decide +kernel)
  exact ⟨(38568518817/1250000000), (308548150549/10000000000), h.1, h.2⟩

def log_65 : Enclosure (Real.log ((27991385387593727036773891112005220881/1000000000000000000000000) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (27991385387593727036773891112005220881/1000000000000000000000000) (44) 12 1000000000000
    (61925835827/2000000000) (309629179149/10000000000) (by decide +kernel)
  exact ⟨(61925835827/2000000000), (309629179149/10000000000), h.1, h.2⟩

def pairLogs_1 : ∀ i, Enclosure (Real.log ((pairBound 0 3 (h158PhaseRoots 0 i) : ℚ) : ℝ)) := by
  refine Fin.cases ?_ ?_
  · exact log_62.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_63.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_64.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_65.ofRatEq (by decide +kernel)
  exact fun i => Fin.elim0 i

theorem endpoint_1_first_cell {s : ℝ} (hs : 0 ≤ s ∧ s ≤ 3)
    (hpositive : ∀ j, 0 < h158AdaptivePairModulus 75 (h158PhaseRoots 0 j : ℝ) s) :
    h158PhasePotential (fun j => (h158PhaseRoots 0 j : ℝ)) (1/4) s ≤ ((-518023/1000) : ℝ) := by
  have h := potential_cell_le (fun j => (h158PhaseRoots 0 j : ℝ))
    (theta := (1/4)) (by norm_num) (first_phase_cell hs)
    (fun j => (pairBound 0 3 (h158PhaseRoots 0 j) : ℝ))
    (fun j => ((pairLogs_1 j).hi : ℝ)) hpositive
    (fun j => pair_le_pairBound 0 3 (h158PhaseRoots 0 j) (by norm_num)
      (by have hq := (h158PhaseRoots_bounds (0 : Fin 8) j).1.le; exact_mod_cast hq) (by simpa using hs))
    (fun j => (pairLogs_1 j).upper)
  have hq : ((-2705260589693/5000000000) : ℚ)+(1/4)/8*∑ j, (pairLogs_1 j).hi ≤ (-518023/1000) := by decide +kernel
  have hreal : ((((-2705260589693/5000000000) : ℚ)+(1/4)/8*∑ j, (pairLogs_1 j).hi : ℚ) : ℝ) ≤ ((-518023/1000) : ℚ) := Rat.cast_le.mpr hq
  apply h.trans
  push_cast at hreal
  norm_num at hreal ⊢
  exact hreal

def log_66 : Enclosure (Real.log ((181520224570969290515967377641/10000000000000000) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (181520224570969290515967377641/10000000000000000) (44) 12 1000000000000
    (305298031001/10000000000) (152649015507/5000000000) (by decide +kernel)
  exact ⟨(305298031001/10000000000), (152649015507/5000000000), h.1, h.2⟩

def log_67 : Enclosure (Real.log ((86336239755604166784068254802330521/3906250000000000000000) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (86336239755604166784068254802330521/3906250000000000000000) (44) 12 1000000000000
    (61453385437/2000000000) (153633463599/5000000000) (by decide +kernel)
  exact ⟨(61453385437/2000000000), (153633463599/5000000000), h.1, h.2⟩

def log_68 : Enclosure (Real.log ((102957729190030921877664897241723801/3906250000000000000000) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (102957729190030921877664897241723801/3906250000000000000000) (44) 12 1000000000000
    (309027617887/10000000000) (3090276179/100000000) (by decide +kernel)
  exact ⟨(309027617887/10000000000), (3090276179/100000000), h.1, h.2⟩

def log_69 : Enclosure (Real.log ((123799840467156639587933519298864201/3906250000000000000000) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (123799840467156639587933519298864201/3906250000000000000000) (44) 12 1000000000000
    (12434843741/400000000) (310871093539/10000000000) (by decide +kernel)
  exact ⟨(12434843741/400000000), (310871093539/10000000000), h.1, h.2⟩

def pairLogs_2 : ∀ i, Enclosure (Real.log ((pairBound 0 3 (h158PhaseRoots 1 i) : ℚ) : ℝ)) := by
  refine Fin.cases ?_ ?_
  · exact log_66.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_67.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_68.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_69.ofRatEq (by decide +kernel)
  exact fun i => Fin.elim0 i

theorem endpoint_2_first_cell {s : ℝ} (hs : 0 ≤ s ∧ s ≤ 3)
    (hpositive : ∀ j, 0 < h158AdaptivePairModulus 75 (h158PhaseRoots 1 j : ℝ) s) :
    h158PhasePotential (fun j => (h158PhaseRoots 1 j : ℝ)) (1/4) s ≤ ((-64751/125) : ℝ) := by
  have h := potential_cell_le (fun j => (h158PhaseRoots 1 j : ℝ))
    (theta := (1/4)) (by norm_num) (first_phase_cell hs)
    (fun j => (pairBound 0 3 (h158PhaseRoots 1 j) : ℝ))
    (fun j => ((pairLogs_2 j).hi : ℝ)) hpositive
    (fun j => pair_le_pairBound 0 3 (h158PhaseRoots 1 j) (by norm_num)
      (by have hq := (h158PhaseRoots_bounds (1 : Fin 8) j).1.le; exact_mod_cast hq) (by simpa using hs))
    (fun j => (pairLogs_2 j).upper)
  have hq : ((-2705260589693/5000000000) : ℚ)+(1/4)/8*∑ j, (pairLogs_2 j).hi ≤ (-64751/125) := by decide +kernel
  have hreal : ((((-2705260589693/5000000000) : ℚ)+(1/4)/8*∑ j, (pairLogs_2 j).hi : ℚ) : ℝ) ≤ ((-64751/125) : ℚ) := Rat.cast_le.mpr hq
  apply h.trans
  push_cast at hreal
  norm_num at hreal ⊢
  exact hreal

def pairLogs_3 : ∀ i, Enclosure (Real.log ((pairBound 0 3 (h158PhaseRoots 1 i) : ℚ) : ℝ)) := by
  refine Fin.cases ?_ ?_
  · exact log_66.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_67.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_68.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_69.ofRatEq (by decide +kernel)
  exact fun i => Fin.elim0 i

theorem endpoint_3_first_cell {s : ℝ} (hs : 0 ≤ s ∧ s ≤ 3)
    (hpositive : ∀ j, 0 < h158AdaptivePairModulus 75 (h158PhaseRoots 1 j : ℝ) s) :
    h158PhasePotential (fun j => (h158PhaseRoots 1 j : ℝ)) (1/2) s ≤ ((-514683/1000) : ℝ) := by
  have h := potential_cell_le (fun j => (h158PhaseRoots 1 j : ℝ))
    (theta := (1/2)) (by norm_num) (first_phase_cell hs)
    (fun j => (pairBound 0 3 (h158PhaseRoots 1 j) : ℝ))
    (fun j => ((pairLogs_3 j).hi : ℝ)) hpositive
    (fun j => pair_le_pairBound 0 3 (h158PhaseRoots 1 j) (by norm_num)
      (by have hq := (h158PhaseRoots_bounds (1 : Fin 8) j).1.le; exact_mod_cast hq) (by simpa using hs))
    (fun j => (pairLogs_3 j).upper)
  have hq : ((-2705260589693/5000000000) : ℚ)+(1/2)/8*∑ j, (pairLogs_3 j).hi ≤ (-514683/1000) := by decide +kernel
  have hreal : ((((-2705260589693/5000000000) : ℚ)+(1/2)/8*∑ j, (pairLogs_3 j).hi : ℚ) : ℝ) ≤ ((-514683/1000) : ℚ) := Rat.cast_le.mpr hq
  apply h.trans
  push_cast at hreal
  norm_num at hreal ⊢
  exact hreal

def log_70 : Enclosure (Real.log ((65862970563559737328975233036549961/3906250000000000000000) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (65862970563559737328975233036549961/3906250000000000000000) (43) 12 1000000000000
    (304560196611/10000000000) (19035012289/625000000) (by decide +kernel)
  exact ⟨(304560196611/10000000000), (19035012289/625000000), h.1, h.2⟩

def log_71 : Enclosure (Real.log ((85081343521058130336404466754683081/3906250000000000000000) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (85081343521058130336404466754683081/3906250000000000000000) (44) 12 1000000000000
    (9597515957/312500000) (307120510637/10000000000) (by decide +kernel)
  exact ⟨(9597515957/312500000), (307120510637/10000000000), h.1, h.2⟩

def log_72 : Enclosure (Real.log ((416892377109453295870486893580921/15258789062500000000) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (416892377109453295870486893580921/15258789062500000000) (44) 12 1000000000000
    (38673366933/1250000000) (154693467739/5000000000) (by decide +kernel)
  exact ⟨(38673366933/1250000000), (154693467739/5000000000), h.1, h.2⟩

def log_73 : Enclosure (Real.log ((88500507096088802194781930101681/2560000000000000000) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (88500507096088802194781930101681/2560000000000000000) (44) 12 1000000000000
    (77935055347/2500000000) (311740221401/10000000000) (by decide +kernel)
  exact ⟨(77935055347/2500000000), (311740221401/10000000000), h.1, h.2⟩

def pairLogs_4 : ∀ i, Enclosure (Real.log ((pairBound 0 3 (h158PhaseRoots 2 i) : ℚ) : ℝ)) := by
  refine Fin.cases ?_ ?_
  · exact log_70.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_71.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_72.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_73.ofRatEq (by decide +kernel)
  exact fun i => Fin.elim0 i

theorem endpoint_4_first_cell {s : ℝ} (hs : 0 ≤ s ∧ s ≤ 3)
    (hpositive : ∀ j, 0 < h158AdaptivePairModulus 75 (h158PhaseRoots 2 j : ℝ) s) :
    h158PhasePotential (fun j => (h158PhaseRoots 2 j : ℝ)) (1/2) s ≤ ((-257333/500) : ℝ) := by
  have h := potential_cell_le (fun j => (h158PhaseRoots 2 j : ℝ))
    (theta := (1/2)) (by norm_num) (first_phase_cell hs)
    (fun j => (pairBound 0 3 (h158PhaseRoots 2 j) : ℝ))
    (fun j => ((pairLogs_4 j).hi : ℝ)) hpositive
    (fun j => pair_le_pairBound 0 3 (h158PhaseRoots 2 j) (by norm_num)
      (by have hq := (h158PhaseRoots_bounds (2 : Fin 8) j).1.le; exact_mod_cast hq) (by simpa using hs))
    (fun j => (pairLogs_4 j).upper)
  have hq : ((-2705260589693/5000000000) : ℚ)+(1/2)/8*∑ j, (pairLogs_4 j).hi ≤ (-257333/500) := by decide +kernel
  have hreal : ((((-2705260589693/5000000000) : ℚ)+(1/2)/8*∑ j, (pairLogs_4 j).hi : ℚ) : ℝ) ≤ ((-257333/500) : ℚ) := Rat.cast_le.mpr hq
  apply h.trans
  push_cast at hreal
  norm_num at hreal ⊢
  exact hreal

def pairLogs_5 : ∀ i, Enclosure (Real.log ((pairBound 0 3 (h158PhaseRoots 2 i) : ℚ) : ℝ)) := by
  refine Fin.cases ?_ ?_
  · exact log_70.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_71.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_72.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_73.ofRatEq (by decide +kernel)
  exact fun i => Fin.elim0 i

theorem endpoint_5_first_cell {s : ℝ} (hs : 0 ≤ s ∧ s ≤ 3)
    (hpositive : ∀ j, 0 < h158AdaptivePairModulus 75 (h158PhaseRoots 2 j : ℝ) s) :
    h158PhasePotential (fun j => (h158PhaseRoots 2 j : ℝ)) (3/4) s ≤ ((-511277/1000) : ℝ) := by
  have h := potential_cell_le (fun j => (h158PhaseRoots 2 j : ℝ))
    (theta := (3/4)) (by norm_num) (first_phase_cell hs)
    (fun j => (pairBound 0 3 (h158PhaseRoots 2 j) : ℝ))
    (fun j => ((pairLogs_5 j).hi : ℝ)) hpositive
    (fun j => pair_le_pairBound 0 3 (h158PhaseRoots 2 j) (by norm_num)
      (by have hq := (h158PhaseRoots_bounds (2 : Fin 8) j).1.le; exact_mod_cast hq) (by simpa using hs))
    (fun j => (pairLogs_5 j).upper)
  have hq : ((-2705260589693/5000000000) : ℚ)+(3/4)/8*∑ j, (pairLogs_5 j).hi ≤ (-511277/1000) := by decide +kernel
  have hreal : ((((-2705260589693/5000000000) : ℚ)+(3/4)/8*∑ j, (pairLogs_5 j).hi : ℚ) : ℝ) ≤ ((-511277/1000) : ℚ) := Rat.cast_le.mpr hq
  apply h.trans
  push_cast at hreal
  norm_num at hreal ⊢
  exact hreal

def log_74 : Enclosure (Real.log ((947735099987888812409791266816/59604644775390625) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (947735099987888812409791266816/59604644775390625) (43) 12 1000000000000
    (303973626447/10000000000) (15198681323/500000000) (by decide +kernel)
  exact ⟨(303973626447/10000000000), (15198681323/500000000), h.1, h.2⟩

def log_75 : Enclosure (Real.log ((21566594814546852661973963040612163921/1000000000000000000000000) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (21566594814546852661973963040612163921/1000000000000000000000000) (44) 12 1000000000000
    (153510833483/5000000000) (15351083349/500000000) (by decide +kernel)
  exact ⟨(153510833483/5000000000), (15351083349/500000000), h.1, h.2⟩

def log_76 : Enclosure (Real.log ((72153752346068876735350619543761/2560000000000000000) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (72153752346068876735350619543761/2560000000000000000) (44) 12 1000000000000
    (77424532871/2500000000) (309698131497/10000000000) (by decide +kernel)
  exact ⟨(77424532871/2500000000), (309698131497/10000000000), h.1, h.2⟩

def log_77 : Enclosure (Real.log ((37133372491328363657984356548968317521/1000000000000000000000000) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (37133372491328363657984356548968317521/1000000000000000000000000) (45) 12 1000000000000
    (39056921511/1250000000) (312455372101/10000000000) (by decide +kernel)
  exact ⟨(39056921511/1250000000), (312455372101/10000000000), h.1, h.2⟩

def pairLogs_6 : ∀ i, Enclosure (Real.log ((pairBound 0 3 (h158PhaseRoots 3 i) : ℚ) : ℝ)) := by
  refine Fin.cases ?_ ?_
  · exact log_74.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_75.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_76.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_77.ofRatEq (by decide +kernel)
  exact fun i => Fin.elim0 i

theorem endpoint_6_first_cell {s : ℝ} (hs : 0 ≤ s ∧ s ≤ 3)
    (hpositive : ∀ j, 0 < h158AdaptivePairModulus 75 (h158PhaseRoots 3 j : ℝ) s) :
    h158PhasePotential (fun j => (h158PhaseRoots 3 j : ℝ)) (3/4) s ≤ ((-25563/50) : ℝ) := by
  have h := potential_cell_le (fun j => (h158PhaseRoots 3 j : ℝ))
    (theta := (3/4)) (by norm_num) (first_phase_cell hs)
    (fun j => (pairBound 0 3 (h158PhaseRoots 3 j) : ℝ))
    (fun j => ((pairLogs_6 j).hi : ℝ)) hpositive
    (fun j => pair_le_pairBound 0 3 (h158PhaseRoots 3 j) (by norm_num)
      (by have hq := (h158PhaseRoots_bounds (3 : Fin 8) j).1.le; exact_mod_cast hq) (by simpa using hs))
    (fun j => (pairLogs_6 j).upper)
  have hq : ((-2705260589693/5000000000) : ℚ)+(3/4)/8*∑ j, (pairLogs_6 j).hi ≤ (-25563/50) := by decide +kernel
  have hreal : ((((-2705260589693/5000000000) : ℚ)+(3/4)/8*∑ j, (pairLogs_6 j).hi : ℚ) : ℝ) ≤ ((-25563/50) : ℚ) := Rat.cast_le.mpr hq
  apply h.trans
  push_cast at hreal
  norm_num at hreal ⊢
  exact hreal

def pairLogs_7 : ∀ i, Enclosure (Real.log ((pairBound 0 3 (h158PhaseRoots 3 i) : ℚ) : ℝ)) := by
  refine Fin.cases ?_ ?_
  · exact log_74.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_75.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_76.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_77.ofRatEq (by decide +kernel)
  exact fun i => Fin.elim0 i

theorem endpoint_7_first_cell {s : ℝ} (hs : 0 ≤ s ∧ s ≤ 3)
    (hpositive : ∀ j, 0 < h158AdaptivePairModulus 75 (h158PhaseRoots 3 j : ℝ) s) :
    h158PhasePotential (fun j => (h158PhaseRoots 3 j : ℝ)) 1 s ≤ ((-126957/250) : ℝ) := by
  have h := potential_cell_le (fun j => (h158PhaseRoots 3 j : ℝ))
    (theta := 1) (by norm_num) (first_phase_cell hs)
    (fun j => (pairBound 0 3 (h158PhaseRoots 3 j) : ℝ))
    (fun j => ((pairLogs_7 j).hi : ℝ)) hpositive
    (fun j => pair_le_pairBound 0 3 (h158PhaseRoots 3 j) (by norm_num)
      (by have hq := (h158PhaseRoots_bounds (3 : Fin 8) j).1.le; exact_mod_cast hq) (by simpa using hs))
    (fun j => (pairLogs_7 j).upper)
  have hq : ((-2705260589693/5000000000) : ℚ)+1/8*∑ j, (pairLogs_7 j).hi ≤ (-126957/250) := by decide +kernel
  have hreal : ((((-2705260589693/5000000000) : ℚ)+1/8*∑ j, (pairLogs_7 j).hi : ℚ) : ℝ) ≤ ((-126957/250) : ℚ) := Rat.cast_le.mpr hq
  apply h.trans
  push_cast at hreal
  norm_num at hreal ⊢
  exact hreal

def log_78 : Enclosure (Real.log ((15135105374912003472506997795954567121/1000000000000000000000000) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (15135105374912003472506997795954567121/1000000000000000000000000) (43) 12 1000000000000
    (151740190101/5000000000) (60696076043/2000000000) (by decide +kernel)
  exact ⟨(151740190101/5000000000), (60696076043/2000000000), h.1, h.2⟩

def log_79 : Enclosure (Real.log ((83650599390045744651962983838105241/3906250000000000000000) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (83650599390045744651962983838105241/3906250000000000000000) (44) 12 1000000000000
    (153475459369/5000000000) (306950918751/10000000000) (by decide +kernel)
  exact ⟨(153475459369/5000000000), (306950918751/10000000000), h.1, h.2⟩

def log_80 : Enclosure (Real.log ((442395265865236311353033329933401/15258789062500000000) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (442395265865236311353033329933401/15258789062500000000) (44) 12 1000000000000
    (77495172989/2500000000) (309980691969/10000000000) (by decide +kernel)
  exact ⟨(77495172989/2500000000), (309980691969/10000000000), h.1, h.2⟩

def log_81 : Enclosure (Real.log ((101191992611003533935235788559441/2560000000000000000) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (101191992611003533935235788559441/2560000000000000000) (45) 12 1000000000000
    (313080334863/10000000000) (78270083719/2500000000) (by decide +kernel)
  exact ⟨(313080334863/10000000000), (78270083719/2500000000), h.1, h.2⟩

def pairLogs_8 : ∀ i, Enclosure (Real.log ((pairBound 0 3 (h158PhaseRoots 4 i) : ℚ) : ℝ)) := by
  refine Fin.cases ?_ ?_
  · exact log_78.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_79.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_80.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_81.ofRatEq (by decide +kernel)
  exact fun i => Fin.elim0 i

theorem endpoint_8_first_cell {s : ℝ} (hs : 0 ≤ s ∧ s ≤ 3)
    (hpositive : ∀ j, 0 < h158AdaptivePairModulus 75 (h158PhaseRoots 4 j : ℝ) s) :
    h158PhasePotential (fun j => (h158PhaseRoots 4 j : ℝ)) 1 s ≤ ((-507811/1000) : ℝ) := by
  have h := potential_cell_le (fun j => (h158PhaseRoots 4 j : ℝ))
    (theta := 1) (by norm_num) (first_phase_cell hs)
    (fun j => (pairBound 0 3 (h158PhaseRoots 4 j) : ℝ))
    (fun j => ((pairLogs_8 j).hi : ℝ)) hpositive
    (fun j => pair_le_pairBound 0 3 (h158PhaseRoots 4 j) (by norm_num)
      (by have hq := (h158PhaseRoots_bounds (4 : Fin 8) j).1.le; exact_mod_cast hq) (by simpa using hs))
    (fun j => (pairLogs_8 j).upper)
  have hq : ((-2705260589693/5000000000) : ℚ)+1/8*∑ j, (pairLogs_8 j).hi ≤ (-507811/1000) := by decide +kernel
  have hreal : ((((-2705260589693/5000000000) : ℚ)+1/8*∑ j, (pairLogs_8 j).hi : ℚ) : ℝ) ≤ ((-507811/1000) : ℚ) := Rat.cast_le.mpr hq
  apply h.trans
  push_cast at hreal
  norm_num at hreal ⊢
  exact hreal

def pairLogs_9 : ∀ i, Enclosure (Real.log ((pairBound 0 3 (h158PhaseRoots 4 i) : ℚ) : ℝ)) := by
  refine Fin.cases ?_ ?_
  · exact log_78.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_79.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_80.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_81.ofRatEq (by decide +kernel)
  exact fun i => Fin.elim0 i

theorem endpoint_9_first_cell {s : ℝ} (hs : 0 ≤ s ∧ s ≤ 3)
    (hpositive : ∀ j, 0 < h158AdaptivePairModulus 75 (h158PhaseRoots 4 j : ℝ) s) :
    h158PhasePotential (fun j => (h158PhaseRoots 4 j : ℝ)) (5/4) s ≤ ((-252173/500) : ℝ) := by
  have h := potential_cell_le (fun j => (h158PhaseRoots 4 j : ℝ))
    (theta := (5/4)) (by norm_num) (first_phase_cell hs)
    (fun j => (pairBound 0 3 (h158PhaseRoots 4 j) : ℝ))
    (fun j => ((pairLogs_9 j).hi : ℝ)) hpositive
    (fun j => pair_le_pairBound 0 3 (h158PhaseRoots 4 j) (by norm_num)
      (by have hq := (h158PhaseRoots_bounds (4 : Fin 8) j).1.le; exact_mod_cast hq) (by simpa using hs))
    (fun j => (pairLogs_9 j).upper)
  have hq : ((-2705260589693/5000000000) : ℚ)+(5/4)/8*∑ j, (pairLogs_9 j).hi ≤ (-252173/500) := by decide +kernel
  have hreal : ((((-2705260589693/5000000000) : ℚ)+(5/4)/8*∑ j, (pairLogs_9 j).hi : ℚ) : ℝ) ≤ ((-252173/500) : ℚ) := Rat.cast_le.mpr hq
  apply h.trans
  push_cast at hreal
  norm_num at hreal ⊢
  exact hreal

def log_82 : Enclosure (Real.log ((14492597048998399317210483324331341361/1000000000000000000000000) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (14492597048998399317210483324331341361/1000000000000000000000000) (43) 12 1000000000000
    (151523295431/5000000000) (151523295437/5000000000) (by decide +kernel)
  exact ⟨(151523295431/5000000000), (151523295437/5000000000), h.1, h.2⟩

def log_83 : Enclosure (Real.log ((325097459736799801770462268429281/15258789062500000000) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (325097459736799801770462268429281/15258789062500000000) (44) 12 1000000000000
    (306899904599/10000000000) (76724976153/2500000000) (by decide +kernel)
  exact ⟨(306899904599/10000000000), (76724976153/2500000000), h.1, h.2⟩

def log_84 : Enclosure (Real.log ((1774041606519456950875169581696/59604644775390625) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (1774041606519456950875169581696/59604644775390625) (44) 12 1000000000000
    (7756075807/250000000) (310243032293/10000000000) (by decide +kernel)
  exact ⟨(7756075807/250000000), (310243032293/10000000000), h.1, h.2⟩

def log_85 : Enclosure (Real.log ((41816271093101794796785602411912717681/1000000000000000000000000) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (41816271093101794796785602411912717681/1000000000000000000000000) (45) 12 1000000000000
    (156821533199/5000000000) (78410766603/2500000000) (by decide +kernel)
  exact ⟨(156821533199/5000000000), (78410766603/2500000000), h.1, h.2⟩

def pairLogs_10 : ∀ i, Enclosure (Real.log ((pairBound 0 3 (h158PhaseRoots 5 i) : ℚ) : ℝ)) := by
  refine Fin.cases ?_ ?_
  · exact log_82.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_83.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_84.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_85.ofRatEq (by decide +kernel)
  exact fun i => Fin.elim0 i

theorem endpoint_10_first_cell {s : ℝ} (hs : 0 ≤ s ∧ s ≤ 3)
    (hpositive : ∀ j, 0 < h158AdaptivePairModulus 75 (h158PhaseRoots 5 j : ℝ) s) :
    h158PhasePotential (fun j => (h158PhaseRoots 5 j : ℝ)) (5/4) s ≤ ((-50433/100) : ℝ) := by
  have h := potential_cell_le (fun j => (h158PhaseRoots 5 j : ℝ))
    (theta := (5/4)) (by norm_num) (first_phase_cell hs)
    (fun j => (pairBound 0 3 (h158PhaseRoots 5 j) : ℝ))
    (fun j => ((pairLogs_10 j).hi : ℝ)) hpositive
    (fun j => pair_le_pairBound 0 3 (h158PhaseRoots 5 j) (by norm_num)
      (by have hq := (h158PhaseRoots_bounds (5 : Fin 8) j).1.le; exact_mod_cast hq) (by simpa using hs))
    (fun j => (pairLogs_10 j).upper)
  have hq : ((-2705260589693/5000000000) : ℚ)+(5/4)/8*∑ j, (pairLogs_10 j).hi ≤ (-50433/100) := by decide +kernel
  have hreal : ((((-2705260589693/5000000000) : ℚ)+(5/4)/8*∑ j, (pairLogs_10 j).hi : ℚ) : ℝ) ≤ ((-50433/100) : ℚ) := Rat.cast_le.mpr hq
  apply h.trans
  push_cast at hreal
  norm_num at hreal ⊢
  exact hreal

def pairLogs_11 : ∀ i, Enclosure (Real.log ((pairBound 0 3 (h158PhaseRoots 5 i) : ℚ) : ℝ)) := by
  refine Fin.cases ?_ ?_
  · exact log_82.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_83.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_84.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_85.ofRatEq (by decide +kernel)
  exact fun i => Fin.elim0 i

theorem endpoint_11_first_cell {s : ℝ} (hs : 0 ≤ s ∧ s ≤ 3)
    (hpositive : ∀ j, 0 < h158AdaptivePairModulus 75 (h158PhaseRoots 5 j : ℝ) s) :
    h158PhasePotential (fun j => (h158PhaseRoots 5 j : ℝ)) (3/2) s ≤ ((-500839/1000) : ℝ) := by
  have h := potential_cell_le (fun j => (h158PhaseRoots 5 j : ℝ))
    (theta := (3/2)) (by norm_num) (first_phase_cell hs)
    (fun j => (pairBound 0 3 (h158PhaseRoots 5 j) : ℝ))
    (fun j => ((pairLogs_11 j).hi : ℝ)) hpositive
    (fun j => pair_le_pairBound 0 3 (h158PhaseRoots 5 j) (by norm_num)
      (by have hq := (h158PhaseRoots_bounds (5 : Fin 8) j).1.le; exact_mod_cast hq) (by simpa using hs))
    (fun j => (pairLogs_11 j).upper)
  have hq : ((-2705260589693/5000000000) : ℚ)+(3/2)/8*∑ j, (pairLogs_11 j).hi ≤ (-500839/1000) := by decide +kernel
  have hreal : ((((-2705260589693/5000000000) : ℚ)+(3/2)/8*∑ j, (pairLogs_11 j).hi : ℚ) : ℝ) ≤ ((-500839/1000) : ℚ) := Rat.cast_le.mpr hq
  apply h.trans
  push_cast at hreal
  norm_num at hreal ⊢
  exact hreal

def log_86 : Enclosure (Real.log ((831205558083638760455040038536/59604644775390625) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (831205558083638760455040038536/59604644775390625) (43) 12 1000000000000
    (60532329477/2000000000) (151330823699/5000000000) (by decide +kernel)
  exact ⟨(60532329477/2000000000), (151330823699/5000000000), h.1, h.2⟩

def log_87 : Enclosure (Real.log ((1265595939518217982346293611336/59604644775390625) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (1265595939518217982346293611336/59604644775390625) (44) 12 1000000000000
    (153432930003/5000000000) (306865860019/10000000000) (by decide +kernel)
  exact ⟨(153432930003/5000000000), (306865860019/10000000000), h.1, h.2⟩

def log_88 : Enclosure (Real.log ((119148319139482385343933211827873241/3906250000000000000000) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (119148319139482385343933211827873241/3906250000000000000000) (44) 12 1000000000000
    (310488123773/10000000000) (155244061893/5000000000) (by decide +kernel)
  exact ⟨(310488123773/10000000000), (155244061893/5000000000), h.1, h.2⟩

def log_89 : Enclosure (Real.log ((171973752968706183570551485513020361/3906250000000000000000) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (171973752968706183570551485513020361/3906250000000000000000) (45) 12 1000000000000
    (314157851471/10000000000) (78539462871/2500000000) (by decide +kernel)
  exact ⟨(314157851471/10000000000), (78539462871/2500000000), h.1, h.2⟩

def pairLogs_12 : ∀ i, Enclosure (Real.log ((pairBound 0 3 (h158PhaseRoots 6 i) : ℚ) : ℝ)) := by
  refine Fin.cases ?_ ?_
  · exact log_86.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_87.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_88.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_89.ofRatEq (by decide +kernel)
  exact fun i => Fin.elim0 i

theorem endpoint_12_first_cell {s : ℝ} (hs : 0 ≤ s ∧ s ≤ 3)
    (hpositive : ∀ j, 0 < h158AdaptivePairModulus 75 (h158PhaseRoots 6 j : ℝ) s) :
    h158PhasePotential (fun j => (h158PhaseRoots 6 j : ℝ)) (3/2) s ≤ ((-62603/125) : ℝ) := by
  have h := potential_cell_le (fun j => (h158PhaseRoots 6 j : ℝ))
    (theta := (3/2)) (by norm_num) (first_phase_cell hs)
    (fun j => (pairBound 0 3 (h158PhaseRoots 6 j) : ℝ))
    (fun j => ((pairLogs_12 j).hi : ℝ)) hpositive
    (fun j => pair_le_pairBound 0 3 (h158PhaseRoots 6 j) (by norm_num)
      (by have hq := (h158PhaseRoots_bounds (6 : Fin 8) j).1.le; exact_mod_cast hq) (by simpa using hs))
    (fun j => (pairLogs_12 j).upper)
  have hq : ((-2705260589693/5000000000) : ℚ)+(3/2)/8*∑ j, (pairLogs_12 j).hi ≤ (-62603/125) := by decide +kernel
  have hreal : ((((-2705260589693/5000000000) : ℚ)+(3/2)/8*∑ j, (pairLogs_12 j).hi : ℚ) : ℝ) ≤ ((-62603/125) : ℚ) := Rat.cast_le.mpr hq
  apply h.trans
  push_cast at hreal
  norm_num at hreal ⊢
  exact hreal

def pairLogs_13 : ∀ i, Enclosure (Real.log ((pairBound 0 3 (h158PhaseRoots 6 i) : ℚ) : ℝ)) := by
  refine Fin.cases ?_ ?_
  · exact log_86.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_87.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_88.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_89.ofRatEq (by decide +kernel)
  exact fun i => Fin.elim0 i

theorem endpoint_13_first_cell {s : ℝ} (hs : 0 ≤ s ∧ s ≤ 3)
    (hpositive : ∀ j, 0 < h158AdaptivePairModulus 75 (h158PhaseRoots 6 j : ℝ) s) :
    h158PhasePotential (fun j => (h158PhaseRoots 6 j : ℝ)) (7/4) s ≤ ((-497309/1000) : ℝ) := by
  have h := potential_cell_le (fun j => (h158PhaseRoots 6 j : ℝ))
    (theta := (7/4)) (by norm_num) (first_phase_cell hs)
    (fun j => (pairBound 0 3 (h158PhaseRoots 6 j) : ℝ))
    (fun j => ((pairLogs_13 j).hi : ℝ)) hpositive
    (fun j => pair_le_pairBound 0 3 (h158PhaseRoots 6 j) (by norm_num)
      (by have hq := (h158PhaseRoots_bounds (6 : Fin 8) j).1.le; exact_mod_cast hq) (by simpa using hs))
    (fun j => (pairLogs_13 j).upper)
  have hq : ((-2705260589693/5000000000) : ℚ)+(7/4)/8*∑ j, (pairLogs_13 j).hi ≤ (-497309/1000) := by decide +kernel
  have hreal : ((((-2705260589693/5000000000) : ℚ)+(7/4)/8*∑ j, (pairLogs_13 j).hi : ℚ) : ℝ) ≤ ((-497309/1000) : ℚ) := Rat.cast_le.mpr hq
  apply h.trans
  push_cast at hreal
  norm_num at hreal ⊢
  exact hreal

def log_90 : Enclosure (Real.log ((13464968293471961401921322154302839921/1000000000000000000000000) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (13464968293471961401921322154302839921/1000000000000000000000000) (43) 12 1000000000000
    (30231112487/1000000000) (302311124883/10000000000) (by decide +kernel)
  exact ⟨(30231112487/1000000000), (302311124883/10000000000), h.1, h.2⟩

def log_91 : Enclosure (Real.log ((21178990813790798987934884659881926481/1000000000000000000000000) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (21178990813790798987934884659881926481/1000000000000000000000000) (44) 12 1000000000000
    (9588759627/312500000) (306840308077/10000000000) (by decide +kernel)
  exact ⟨(9588759627/312500000), (306840308077/10000000000), h.1, h.2⟩

def log_92 : Enclosure (Real.log ((31230046595754343966352090811710476401/1000000000000000000000000) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (31230046595754343966352090811710476401/1000000000000000000000000) (44) 12 1000000000000
    (310724017787/10000000000) (310724017801/10000000000) (by decide +kernel)
  exact ⟨(310724017787/10000000000), (310724017801/10000000000), h.1, h.2⟩

def log_93 : Enclosure (Real.log ((180477285994159503031121200732049881/3906250000000000000000) : ℚ)) := by
  have h := RationalLogBounds.of_checkRounded (180477285994159503031121200732049881/3906250000000000000000) (45) 12 1000000000000
    (157320241057/5000000000) (314640482127/10000000000) (by decide +kernel)
  exact ⟨(157320241057/5000000000), (314640482127/10000000000), h.1, h.2⟩

def pairLogs_14 : ∀ i, Enclosure (Real.log ((pairBound 0 3 (h158PhaseRoots 7 i) : ℚ) : ℝ)) := by
  refine Fin.cases ?_ ?_
  · exact log_90.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_91.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_92.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_93.ofRatEq (by decide +kernel)
  exact fun i => Fin.elim0 i

theorem endpoint_14_first_cell {s : ℝ} (hs : 0 ≤ s ∧ s ≤ 3)
    (hpositive : ∀ j, 0 < h158AdaptivePairModulus 75 (h158PhaseRoots 7 j : ℝ) s) :
    h158PhasePotential (fun j => (h158PhaseRoots 7 j : ℝ)) (7/4) s ≤ ((-99459/200) : ℝ) := by
  have h := potential_cell_le (fun j => (h158PhaseRoots 7 j : ℝ))
    (theta := (7/4)) (by norm_num) (first_phase_cell hs)
    (fun j => (pairBound 0 3 (h158PhaseRoots 7 j) : ℝ))
    (fun j => ((pairLogs_14 j).hi : ℝ)) hpositive
    (fun j => pair_le_pairBound 0 3 (h158PhaseRoots 7 j) (by norm_num)
      (by have hq := (h158PhaseRoots_bounds (7 : Fin 8) j).1.le; exact_mod_cast hq) (by simpa using hs))
    (fun j => (pairLogs_14 j).upper)
  have hq : ((-2705260589693/5000000000) : ℚ)+(7/4)/8*∑ j, (pairLogs_14 j).hi ≤ (-99459/200) := by decide +kernel
  have hreal : ((((-2705260589693/5000000000) : ℚ)+(7/4)/8*∑ j, (pairLogs_14 j).hi : ℚ) : ℝ) ≤ ((-99459/200) : ℚ) := Rat.cast_le.mpr hq
  apply h.trans
  push_cast at hreal
  norm_num at hreal ⊢
  exact hreal

def pairLogs_15 : ∀ i, Enclosure (Real.log ((pairBound 0 3 (h158PhaseRoots 7 i) : ℚ) : ℝ)) := by
  refine Fin.cases ?_ ?_
  · exact log_90.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_91.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_92.ofRatEq (by decide +kernel)
  refine Fin.cases ?_ ?_
  · exact log_93.ofRatEq (by decide +kernel)
  exact fun i => Fin.elim0 i

theorem endpoint_15_first_cell {s : ℝ} (hs : 0 ≤ s ∧ s ≤ 3)
    (hpositive : ∀ j, 0 < h158AdaptivePairModulus 75 (h158PhaseRoots 7 j : ℝ) s) :
    h158PhasePotential (fun j => (h158PhaseRoots 7 j : ℝ)) 2 s ≤ ((-246881/500) : ℝ) := by
  have h := potential_cell_le (fun j => (h158PhaseRoots 7 j : ℝ))
    (theta := 2) (by norm_num) (first_phase_cell hs)
    (fun j => (pairBound 0 3 (h158PhaseRoots 7 j) : ℝ))
    (fun j => ((pairLogs_15 j).hi : ℝ)) hpositive
    (fun j => pair_le_pairBound 0 3 (h158PhaseRoots 7 j) (by norm_num)
      (by have hq := (h158PhaseRoots_bounds (7 : Fin 8) j).1.le; exact_mod_cast hq) (by simpa using hs))
    (fun j => (pairLogs_15 j).upper)
  have hq : ((-2705260589693/5000000000) : ℚ)+2/8*∑ j, (pairLogs_15 j).hi ≤ (-246881/500) := by decide +kernel
  have hreal : ((((-2705260589693/5000000000) : ℚ)+2/8*∑ j, (pairLogs_15 j).hi : ℚ) : ℝ) ≤ ((-246881/500) : ℚ) := Rat.cast_le.mpr hq
  apply h.trans
  push_cast at hreal
  norm_num at hreal ⊢
  exact hreal

theorem first_cell_endpoints (b : Fin 8) (side : Fin 2) {s : ℝ}
    (hs : 0 ≤ s ∧ s ≤ 3) (hne : ∀ j, s ≠ (h158PhaseRoots b j : ℝ)) :
    h158PhasePotential (fun j => (h158PhaseRoots b j : ℝ))
      (((b.val : ℝ)+(side.val : ℝ))/4) s ≤ (h158CompactEndpointCeiling b side : ℝ) := by
  have hpos := h158PhaseRoots_pair_pos b hs.1 hne
  fin_cases b <;> fin_cases side
  · convert endpoint_0_first_cell hs using 1 <;>
      norm_num [h158CompactEndpointCeiling] <;> rfl
  · convert endpoint_1_first_cell hs hpos using 1 <;>
      norm_num [h158CompactEndpointCeiling] <;> rfl
  · convert endpoint_2_first_cell hs hpos using 1 <;>
      norm_num [h158CompactEndpointCeiling] <;> rfl
  · convert endpoint_3_first_cell hs hpos using 1 <;>
      norm_num [h158CompactEndpointCeiling] <;> rfl
  · convert endpoint_4_first_cell hs hpos using 1 <;>
      norm_num [h158CompactEndpointCeiling] <;> rfl
  · convert endpoint_5_first_cell hs hpos using 1 <;>
      norm_num [h158CompactEndpointCeiling] <;> rfl
  · convert endpoint_6_first_cell hs hpos using 1 <;>
      norm_num [h158CompactEndpointCeiling] <;> rfl
  · convert endpoint_7_first_cell hs hpos using 1 <;>
      norm_num [h158CompactEndpointCeiling] <;> rfl
  · convert endpoint_8_first_cell hs hpos using 1 <;>
      norm_num [h158CompactEndpointCeiling] <;> rfl
  · convert endpoint_9_first_cell hs hpos using 1 <;>
      norm_num [h158CompactEndpointCeiling] <;> rfl
  · convert endpoint_10_first_cell hs hpos using 1 <;>
      norm_num [h158CompactEndpointCeiling] <;> rfl
  · convert endpoint_11_first_cell hs hpos using 1 <;>
      norm_num [h158CompactEndpointCeiling] <;> rfl
  · convert endpoint_12_first_cell hs hpos using 1 <;>
      norm_num [h158CompactEndpointCeiling] <;> rfl
  · convert endpoint_13_first_cell hs hpos using 1 <;>
      norm_num [h158CompactEndpointCeiling] <;> rfl
  · convert endpoint_14_first_cell hs hpos using 1 <;>
      norm_num [h158CompactEndpointCeiling] <;> rfl
  · convert endpoint_15_first_cell hs hpos using 1 <;>
      norm_num [h158CompactEndpointCeiling] <;> rfl

end OddZetaMixed.CompactPhase.Certificates

namespace OddZetaMixed

theorem h158CompactPhase_first_cell (b : Fin 8) {theta s : ℝ}
    (hl : (b.val : ℝ)/4 ≤ theta) (hr : theta ≤ ((b.val : ℝ)+1)/4)
    (hs : 0 ≤ s ∧ s ≤ 3) (hne : ∀ j, s ≠ (h158PhaseRoots b j : ℝ)) :
    h158PhasePotential (fun j => (h158PhaseRoots b j : ℝ)) theta s ≤ h158CompactCeiling b theta := by
  apply h158CompactPhase_of_endpoints b hl hr
  · simpa using CompactPhase.Certificates.first_cell_endpoints b 0 hs hne
  · simpa using CompactPhase.Certificates.first_cell_endpoints b 1 hs hne

end OddZetaMixed
